"""Especificaciones: (1) low-ticket con bumps y upsells, (2) webinar gratuito de captación."""
from mf_comun import inicio, GLOSARIO_BASE, chequeos_base, cobranza, objetivos, costos, cash_rows, seguimiento_calc

# ---------------------------------------------------------------- 1. LOW-TICKET
_LT_PRODUCTOS = [
    ("bump1", "Bump 1", 17, (0.18, 0.25, 0.35), "Oferta extra en el checkout del principal (una casilla). % sobre compradores del principal."),
    ("bump2", "Bump 2", 17, (0.12, 0.18, 0.25), "Segundo bump en el mismo checkout. Rinde algo menos que el primero."),
    ("oto1", "OTO 1", 47, (0.07, 0.10, 0.14), "Página 1 después del pago: el primer upsell. % sobre compradores del principal."),
    ("oto2", "OTO 2", 17, (0.04, 0.06, 0.09), "Página 2: suele ser el downsell de la OTO 1 (más barato). El % va sobre todos los compradores, para simplificar."),
    ("oto3", "OTO 3", 97, (0.02, 0.03, 0.05), "Página 3: el segundo upsell."),
    ("oto4", "OTO 4", 27, (0.03, 0.04, 0.06), "Página 4: el downsell del segundo upsell."),
    ("ascension", "Ascensión (programa de mayor valor)", 297, (0.01, 0.02, 0.04), "El upsell de ascensión: el programa que se vende después del embudo, por checkout o por llamada. % sobre compradores del principal."),
]

def _lt_supuestos():
    prods = []
    for k, nombre, precio, esc, nota in _LT_PRODUCTOS:
        prods.append({"key": f"{k}_precio", "label": f"{nombre}: precio", "val": precio, "fmt": "money", "unidad": "USD", "nota": nota})
        prods.append({"key": f"{k}_conv", "label": f"{nombre}: % de compradores que lo toman", "esc": esc, "fmt": "pct", "unidad": "%", "nota": ""})
    return [
        {"grupo": "1. Inversión y tráfico", "items": [
            {"key": "inversion", "label": "Inversión en publicidad por mes", "val": 9000, "fmt": "money0", "unidad": "USD / mes", "nota": "El ejemplo invierte 300 USD por día."},
            {"key": "costo_visita", "label": "Costo por visita a la página de ventas (VSL)", "esc": (0.40, 0.30, 0.22), "fmt": "money", "unidad": "USD / visita", "nota": "Lo que pagás por cada persona que llega a la página. En tráfico frío hispano se mueve entre 0,20 y 0,50."},
        ]},
        {"grupo": "2. Conversión de la página de ventas", "items": [
            {"key": "conv_checkout", "label": "% de visitas que llegan al checkout", "esc": (0.025, 0.035, 0.045), "fmt": "pct", "unidad": "%", "nota": "Visitas que tocan 'comprar' y abren el checkout."},
            {"key": "conv_venta", "label": "% de checkouts que terminan en compra", "esc": (0.20, 0.26, 0.30), "fmt": "pct", "unidad": "%", "nota": "Checkouts que pagan."},
        ]},
        {"grupo": "3. Escalera: producto principal → bumps 1 y 2 → OTO 1 a 4 → ascensión (precio y % sobre compradores del principal)", "items": [
            {"key": "precio_front", "label": "Producto principal: precio", "val": 37, "fmt": "money", "unidad": "USD", "nota": "El producto que vende la VSL. Todo lo demás se mide como % de sus compradores."},
            *prods,
        ]},
        {"grupo": "4. Costos", "items": costos(0.10, 0.0, 0.05, 0.0, "visita", 1500, "mes",
                                                 "Sobre el cash cobrado. En este embudo no hay llamadas: 0 %.",
                                                 "Costos que crecen con el volumen. En venta directa suele ser 0.")},
        {"grupo": "5. Cobranza", "items": cobranza(1.0, 0.0, 0.0, "Pago único digital: 100 % en el mes 1.")},
        {"grupo": "6. Objetivos y proyección", "items": objetivos(2.0, 500, "ventas / mes", 5000, "mes")},
    ]

def _lt_calculo():
    rows = [
        {"seccion": "Tráfico y unidades"},
        {"key": "cpu", "label": "Costo por visita (unidad de adquisición)", "f": "{costo_visita}", "fmt": "money", "como": "El supuesto 'costo por visita'."},
        {"key": "unidades", "label": "Visitas a la página de ventas", "f": "{inversion}/{cpu}", "fmt": "int", "como": "Inversión ÷ costo por visita.", "bold": True},
        {"key": "checkouts", "label": "Checkouts iniciados", "f": "{unidades}*{conv_checkout}", "fmt": "int", "como": "Visitas × % que llega al checkout."},
        {"key": "ventas_front", "label": "Ventas del producto principal", "f": "{checkouts}*{conv_venta}", "fmt": "num1", "como": "Checkouts × % que compra.", "bold": True},
        {"key": "conv_unidad_venta", "label": "% de visitas que compran", "f": "{ventas_front}/{unidades}", "fmt": "pct2", "como": "Ventas ÷ visitas. Las dos conversiones multiplicadas."},
        {"key": "cpa", "label": "Costo por comprador (CPA)", "f": "{inversion}/{ventas_front}", "fmt": "money", "como": "Inversión ÷ ventas del principal.", "bold": True},
        {"seccion": "Facturación por producto"},
        {"key": "fact_front", "label": "Facturado: producto principal", "f": "{ventas_front}*{precio_front}", "fmt": "money0", "como": "Ventas × precio."},
    ]
    for k, nombre, _, _, _ in _LT_PRODUCTOS:
        rows.append({"key": f"ventas_{k}", "label": f"Ventas: {nombre}", "f": f"{{ventas_front}}*{{{k}_conv}}", "fmt": "num1", "como": "Compradores del principal × % que lo toma."})
        rows.append({"key": f"fact_{k}", "label": f"Facturado: {nombre}", "f": f"{{ventas_{k}}}*{{{k}_precio}}", "fmt": "money0", "como": "Ventas × precio."})
    suma = "+".join(["{fact_front}"] + [f"{{fact_{k}}}" for k, *_ in _LT_PRODUCTOS])
    rows += [
        {"key": "facturado", "label": "Facturado total", "f": suma, "fmt": "money0", "como": "Suma de todos los productos.", "bold": True},
        {"key": "aov", "label": "Facturado por comprador (AOV)", "f": "{facturado}/{ventas_front}", "fmt": "money", "como": "Facturado total ÷ ventas del principal.", "bold": True},
        {"key": "aov_ratio", "label": "AOV ÷ precio del principal", "f": "{aov}/{precio_front}", "fmt": "ratio", "como": "Cuánto multiplica la escalera al precio del front."},
        {"key": "ventas_por_unidad", "label": "Ventas del principal por visita (para la proyección)", "f": "{ventas_front}/{unidades}", "fmt": "pct2", "como": "Igual a '% de visitas que compran'."},
        {"key": "fact_por_unidad", "label": "Facturado por visita", "f": "{facturado}/{unidades}", "fmt": "money", "como": "Facturado total ÷ visitas."},
        *cash_rows("visita"),
        {"seccion": "Cuánto vale cada unidad y hasta cuánto pagar"},
        {"key": "vpu", "label": "Valor neto por visita", "f": "({neto}-{semivar})/{unidades}", "fmt": "money", "como": "(Cash neto − costos por unidad) ÷ visitas. Lo que vale una visita.", "bold": True},
        {"key": "techo_cpu", "label": "Techo de costo por visita (break-even)", "f": "{vpu}", "fmt": "money", "como": "Igual al valor neto por visita: pagando esto no ganás ni perdés.", "bold": True},
        {"key": "objetivo_cpu", "label": "Objetivo de costo por visita", "f": "{techo_cpu}/(1+{margen_seg})", "fmt": "money", "como": "Techo ÷ (1 + margen de seguridad).", "bold": True},
        {"key": "techo_checkout", "label": "Techo de costo por checkout", "f": "{vpu}/{conv_checkout}", "fmt": "money", "como": "Valor por visita ÷ % que llega al checkout."},
        {"key": "techo_cpa", "label": "Techo de costo por comprador (CPA máximo)", "f": "{vpu}/{conv_unidad_venta}", "fmt": "money", "como": "Valor por visita ÷ % de visitas que compran.", "bold": True},
        {"key": "objetivo_cpa", "label": "Objetivo de CPA", "f": "{techo_cpa}/(1+{margen_seg})", "fmt": "money", "como": "CPA máximo ÷ (1 + margen de seguridad)."},
        {"key": "aov_neto", "label": "Cash neto por comprador (AOV neto)", "f": "({neto}-{semivar})/{ventas_front}", "fmt": "money", "como": "Lo que deja cada comprador después de comisiones y reembolsos."},
        {"key": "aov_menos_cpa", "label": "AOV neto − CPA (lo que queda por comprador)", "f": "{aov_neto}-{cpa}", "fmt": "money", "como": "Si es negativo, perdés plata con cada venta.", "bold": True},
        {"seccion": "Semáforo y cuánto invertir"},
        {"key": "semaforo", "label": "Semáforo del costo por visita actual", "f": 'IF({cpu}>{techo_cpu},"ROJO",IF(AND({cpu}<={objetivo_cpu},{roas_cash}>={roas_obj}),"VERDE","AMARILLO"))', "fmt": "txt", "como": "Rojo: costo > techo. Verde: costo ≤ objetivo y ROAS sobre cash neto ≥ objetivo. Amarillo: el resto.", "bold": True},
        {"key": "inv_meta", "label": "Inversión necesaria para la meta de ventas (al costo actual)", "f": 'IF({conv_unidad_venta}=0,"inalcanzable con estos supuestos",{meta_ventas}/{conv_unidad_venta}*{cpu})', "fmt": "money0", "como": "Meta ÷ % de visitas que compran × costo por visita.", "bold": True},
        {"key": "inv_meta_obj", "label": "Inversión para la meta al costo objetivo (lo máximo que conviene pagar)", "f": 'IF({conv_unidad_venta}=0,"inalcanzable con estos supuestos",{meta_ventas}/{conv_unidad_venta}*{objetivo_cpu})', "fmt": "money0", "como": "Lo mismo, al costo objetivo."},
    ]
    return rows

LOW_TICKET = {
    "archivo": "01_Modelo_Financiero_Embudo_Low_Ticket_Bumps_Upsells.xlsx",
    "titulo": "Modelo financiero · Embudo low-ticket con bumps y upsells",
    "subtitulo": "Anuncios → página de ventas (VSL) → checkout → producto principal + bumps + OTOs + ascenso",
    "unidad_singular": "visita", "unidad_plural": "visitas",
    "inicio": inicio("embudo de venta directa: anuncios que llevan a una página de ventas con video (VSL), un producto principal de precio bajo y una escalera de bumps, OTOs y un programa de ascenso",
                     ["La unidad que comprás es la visita a la página. El número que manda es la diferencia entre lo que deja cada comprador sumando toda la escalera (AOV neto) y lo que te cuesta conseguirlo (CPA)."],
                     ["Un curso de 37 USD vendido con VSL a tráfico frío. Se invierten 9.000 USD por mes a 0,30 por visita (30.000 visitas). El 3,5 % llega al checkout y el 26 % de esos compra: 273 ventas al mes, CPA de 33 USD.",
                      "La escalera: dos bumps de 17 (25 % y 18 %); cuatro OTOs después del pago, una por página: 47 (10 %), 17 (6 %), 97 (3 %) y 27 (4 %); y la ascensión a un programa de 297 que toma el 2 %. El AOV queda cerca de 60 USD: la escalera multiplica el precio del principal por 1,6.",
                      "Costos: pasarela 10 %, reembolsos 5 %, fijos 1.500 por mes. Pago único: la cobranza entra 100 % el primer mes.",
                      "Resultado: ganancia mensual positiva y ROAS sobre cash neto de 1,5, con techo de costo por visita cerca de 0,46 y objetivo cerca de 0,36. El semáforo queda en amarillo: el costo por visita está bien, pero el ROAS no llega al objetivo de 2. Sensibilidad dice que las palancas son el costo por visita y la conversión de la página, no el precio. Cambiá los números por los tuyos."],
                     "visita", "visitas", "mes",
                     ["8. En este embudo el techo de CPA es el AOV neto. Si tu CPA se acerca al AOV neto, subir los bumps y las OTOs es la forma más rápida de recuperar margen sin tocar el tráfico."]),
    "embudo": [
        {"key": "unidades", "label": "Visitas a la página de ventas (VSL)", "bold": True, "nota": "La unidad que compra la pauta. Costo por visita."},
        {"key": "checkouts", "label": "Abren el checkout", "nota": "Costo por checkout. Si se pierde mucho acá, es la VSL."},
        {"key": "ventas_front", "label": "Compran el producto principal", "bold": True, "nota": "CPA: costo por comprador. Si se pierde mucho acá, es el checkout o la oferta."},
        {"key": "ventas_bump1", "label": "Toman el bump 1", "vs": "ventas_front", "costo": False, "techo": False, "nota": "Sobre compradores del principal. Se pagó con el CPA; suma al AOV."},
        {"key": "ventas_bump2", "label": "Toman el bump 2", "vs": "ventas_front", "costo": False, "techo": False, "nota": "Sobre compradores del principal."},
        {"key": "ventas_oto1", "label": "Toman la OTO 1", "vs": "ventas_front", "costo": False, "techo": False, "nota": "Página 1 después del pago."},
        {"key": "ventas_oto2", "label": "Toman la OTO 2", "vs": "ventas_front", "costo": False, "techo": False, "nota": "Página 2 (downsell de la OTO 1)."},
        {"key": "ventas_oto3", "label": "Toman la OTO 3", "vs": "ventas_front", "costo": False, "techo": False, "nota": "Página 3."},
        {"key": "ventas_oto4", "label": "Toman la OTO 4", "vs": "ventas_front", "costo": False, "techo": False, "nota": "Página 4."},
        {"key": "ventas_ascension", "label": "Ascienden al programa", "vs": "ventas_front", "costo": False, "techo": False, "nota": "Sobre compradores del principal. El AOV neto resultante contra el CPA es lo que decide el embudo."},
    ],
    "ganancia": [{"key": "unidades", "nombre": "visita", "bold": True, "como": "Ganancia del período ÷ visitas. La métrica más valiosa del embudo: resume todo lo que pasa después de la página. Su par es el costo por visita."},
                 {"key": "checkouts", "nombre": "checkout"},
                 {"key": "ventas_front", "nombre": "cliente", "bold": True, "como": "Ganancia del período ÷ compradores del principal. Su par es el CPA; la diferencia entre AOV neto y CPA es lo que queda por cliente antes de fijos."}],
    "supuestos": _lt_supuestos(),
    "calculo": _lt_calculo(),
    "resumen": [
        {"seccion": "Resultado del mes"},
        {"key": "profit", "que": "Cash neto menos costos y menos inversión. Lo que queda."},
        {"key": "roas_cash", "que": "Cada dólar invertido vuelve como esto, ya neto."},
        {"key": "roas_fact", "que": "Sobre facturado. Se infla con cuotas y comisiones: no decidas con este."},
        {"key": "ventas_front", "que": "Ventas del producto principal por mes."},
        {"seccion": "Unit economics"},
        {"key": "aov", "que": "Facturado por comprador sumando toda la escalera."},
        {"key": "cpa", "que": "Lo que te cuesta cada comprador."},
        {"key": "aov_menos_cpa", "que": "Si es negativo, cada venta pierde plata."},
        {"key": "vpu", "que": "Lo que vale una visita en cash neto."},
        {"seccion": "Las dos caras de cada número"},
        {"key": "cpu", "label": "Costo por visita", "que": "Lo que pagás por cada visita."},
        {"key": "gan_unidades", "que": "Lo que te queda por cada visita después de todo. La métrica más valiosa del embudo."},
        {"key": "cpa", "label": "Costo por cliente (CPA)", "que": "Lo que pagás por cada comprador."},
        {"key": "gan_ventas_front", "que": "Lo que te queda por cada comprador después de todo."},
        {"key": "aov", "label": "Order value (AOV)", "que": "Facturado por comprador con toda la escalera."},
        {"key": "aov_neto", "label": "Order value neto (AOV neto)", "que": "Lo mismo después de comisiones, reembolsos y costos por unidad."},
        {"seccion": "Hasta cuánto pagar"},
        {"key": "techo_cpu", "que": "Costo por visita donde no ganás ni perdés."},
        {"key": "objetivo_cpu", "que": "A este costo o menos estás en verde."},
        {"key": "techo_cpa", "que": "CPA máximo si lo demás se mantiene."},
        {"key": "semaforo", "que": "Tu costo por visita actual contra techo y objetivo."},
        {"seccion": "Cuánto invertir y cuánta caja"},
        {"key": "inv_meta", "que": "Para llegar a la meta de ventas de Supuestos, al costo actual."},
        {"key": "caja_necesaria", "label": "Caja que hay que tener (peor momento de la proyección)", "que": "Si da 0, el embudo se autofinancia: cada mes cobra más de lo que invierte."},
        {"key": "caja_minima", "label": "Saldo mínimo de caja con tu caja inicial", "que": "Si es negativo, la caja inicial no alcanza."},
        {"key": "profit_12m", "label": "Ganancia acumulada en 12 meses", "que": "Con la inversión creciendo según el supuesto."},
    ],
    "tablas": [
        {"titulo": "Precio del producto principal × % de checkouts que compran → ganancia del mes", "nota": "Subir el precio suele bajar la conversión: la tabla muestra qué combinación gana.",
         "fila_key": "precio_front", "fila_label": "Precio", "filas": [27, 37, 47, 67, 97], "fila_fmt": "money0",
         "col_key": "conv_venta", "col_label": "% checkout → compra", "cols": [0.18, 0.22, 0.26, 0.30, 0.34], "col_fmt": "pct", "salida": "profit", "salida_fmt": "money0"},
        {"titulo": "Costo por visita × % de visitas que llegan al checkout → ganancia del mes", "nota": "La tabla del tráfico: cuánto podés pagar por visita según lo que convierte la página.",
         "fila_key": "cpu", "fila_label": "Costo por visita", "filas": [0.15, 0.20, 0.25, 0.30, 0.40, 0.50, 0.60], "fila_fmt": "money",
         "col_key": "conv_checkout", "col_label": "% visita → checkout", "cols": [0.02, 0.025, 0.03, 0.035, 0.04, 0.05], "col_fmt": "pct", "salida": "profit", "salida_fmt": "money0"},
    ],
    "tabla_roas": {"titulo": "Cuánto invertir para una facturación objetivo, según el ROAS que querés", "nota": "Inversión = facturación ÷ ROAS. Debajo: cuántas visitas hacen falta y cuánto podés pagar por cada una.",
                   "facturacion": [10000, 20000, 30000, 50000, 100000], "roas": [1.5, 2.0, 2.5, 3.0, 4.0], "unidad_label": "Visitas", "unidad_singular": "visita"},
    "palancas": [
        {"key": "costo_visita", "mult": 0.9, "label": "Costo por visita 10 % más barato (mejor creativo o público)"},
        {"key": "conv_checkout", "mult": 1.1, "label": "10 % más visitas al checkout (mejor VSL)"},
        {"key": "conv_venta", "mult": 1.1, "label": "10 % más checkouts que compran (mejor checkout y oferta)"},
        {"key": "precio_front", "mult": 1.1, "label": "Precio del principal 10 % más alto (misma conversión)"},
        {"key": "bump1_conv", "mult": 1.1, "label": "Bump 1 tomado 10 % más"},
        {"key": "oto1_conv", "mult": 1.1, "label": "OTO 1 tomada 10 % más"},
        {"key": "ascension_conv", "mult": 1.1, "label": "Ascensión al programa 10 % más alta"},
        {"key": "reembolsos", "mult": 0.9, "label": "Reembolsos 10 % más bajos"},
    ],
    "seguimiento": {"periodo": "mes", "filas": [
        {"seccion": "Datos que cargás"},
        {"key": "inversion_r", "label": "Inversión en publicidad", "tipo": "in", "fmt": "money0", "ejemplo": [9000, 9500, 10500]},
        {"key": "visitas_r", "label": "Visitas a la página", "tipo": "in", "fmt": "int", "ejemplo": [30000, 30200, 29000]},
        {"key": "checkouts_r", "label": "Checkouts iniciados", "tipo": "in", "fmt": "int", "ejemplo": [1050, 1030, 980]},
        {"key": "ventas_r", "label": "Ventas del producto principal", "tipo": "in", "fmt": "int", "ejemplo": [273, 262, 240]},
        {"key": "bumps_r", "label": "Ventas de bumps (1 + 2)", "tipo": "in", "fmt": "int", "ejemplo": [117, 110, 95]},
        {"key": "otos_r", "label": "Ventas de OTOs (1 a 4)", "tipo": "in", "fmt": "int", "ejemplo": [63, 58, 52]},
        {"key": "ascension_r", "label": "Ventas de la ascensión (programa)", "tipo": "in", "fmt": "int", "ejemplo": [5, 6, 4]},
        {"key": "fact_r", "label": "Facturado del mes (a precio de lista)", "tipo": "in", "fmt": "money0", "ejemplo": [15900, 15400, 13700]},
        {"key": "cash_r", "label": "Cash cobrado en el mes", "tipo": "in", "fmt": "money0", "ejemplo": [15900, 15400, 13700]},
        {"seccion": "Lo que calcula el modelo"},
        {"key": "cpu_r", "label": "Costo por visita real", "tipo": "f", "f": "{inversion_r}/{visitas_r}", "fmt": "money", "bold": True},
        {"key": "conv_ck_r", "label": "% visitas → checkout", "tipo": "f", "f": "{checkouts_r}/{visitas_r}", "fmt": "pct"},
        {"key": "conv_v_r", "label": "% checkout → compra", "tipo": "f", "f": "{ventas_r}/{checkouts_r}", "fmt": "pct"},
        {"key": "cpa_r", "label": "CPA real", "tipo": "f", "f": "{inversion_r}/{ventas_r}", "fmt": "money"},
        {"key": "aov_r", "label": "Cash por comprador", "tipo": "f", "f": "{cash_r}/{ventas_r}", "fmt": "money"},
        *seguimiento_calc("inversion_r", "visitas_r", "fact_r", "cash_r"),
    ]},
    "benchmarks": [
        {"metrica": "Costo por visita a la VSL (USD)", "niveles": [">0,60", "0,35 a 0,60", "0,20 a 0,35", "<0,20"], "key": "cpu", "fuente": "Embudos hispanos de venta directa a tráfico frío, 2025 a 2026."},
        {"metrica": "% visitas → checkout", "niveles": ["<2 %", "2 a 3 %", "3 a 5 %", ">5 %"], "key": "conv_checkout", "fuente": "Idem."},
        {"metrica": "% checkout → compra", "niveles": ["<15 %", "15 a 22 %", "22 a 30 %", ">30 %"], "key": "conv_venta", "fuente": "Idem."},
        {"metrica": "% visitas → compra", "niveles": ["<0,5 %", "0,5 a 0,9 %", "0,9 a 1,5 %", ">1,5 %"], "key": "conv_unidad_venta", "fuente": "Idem."},
        {"metrica": "Bump 1 tomado (% de compradores)", "niveles": ["<15 %", "15 a 25 %", "25 a 35 %", ">35 %"], "key": "bump1_conv", "fuente": "Mercado USA: 30 a 40 % (SamCart, sobre miles de millones procesados). Hispano: 17 a 25 % es lo común."},
        {"metrica": "OTO 1 tomada (% de compradores)", "niveles": ["<5 %", "5 a 9 %", "9 a 14 %", ">14 %"], "key": "oto1_conv", "fuente": "Mercado: 8 a 18 % en info-productos."},
        {"metrica": "Ascensión al programa (% de compradores)", "niveles": ["<1 %", "1 a 2 %", "2 a 4 %", ">4 %"], "key": "ascension_conv", "fuente": "Ascenso front → programa de 300 a 1.000 USD."},
        {"metrica": "AOV ÷ precio del principal", "niveles": ["<1,2", "1,2 a 1,4", "1,4 a 1,7", ">1,7"], "key": "aov_ratio", "fuente": "Cuánto multiplica la escalera."},
        {"metrica": "ROAS sobre cash neto", "niveles": ["<1,2", "1,2 a 1,6", "1,6 a 2,5", ">2,5"], "key": "roas_cash", "fuente": "Tráfico frío. Con backend por llamada sube."},
        {"metrica": "Reembolsos", "niveles": [">10 %", "7 a 10 %", "4 a 7 %", "<4 %"], "key": "reembolsos", "fuente": "Más de 10 % es un problema de oferta."},
    ],
    "glosario": GLOSARIO_BASE + [("OTO 1 a 4", "La secuencia de hasta cuatro páginas después del pago: upsell, downsell, upsell, downsell. Cada una se mide como % de los compradores del principal.", "Supuestos"),
                                 ("Ascensión", "El upsell de mayor valor que se ofrece después del embudo (un programa de 300 a 1.000 USD), por checkout o por llamada.", "Supuestos")],
    "chequeos": chequeos_base(["conv_checkout", "conv_venta", "bump1_conv", "bump2_conv", "oto1_conv", "oto2_conv", "oto3_conv", "oto4_conv", "ascension_conv"],
                              [("unidades", "checkouts"), ("checkouts", "ventas_front")], positivos=["costo_visita", "conv_checkout", "conv_venta"]),
}

# ---------------------------------------------------------------- 2. WEBINAR GRATUITO
WEBINAR_GRATUITO = {
    "archivo": "02_Modelo_Financiero_Embudo_Webinar_Gratuito.xlsx",
    "titulo": "Modelo financiero · Embudo de webinar gratuito",
    "subtitulo": "Anuncios → landing de registro → grupo de WhatsApp → webinar en vivo y replay → oferta + bump + programa superior",
    "unidad_singular": "registro", "unidad_plural": "registros",
    "ganancia": [{"key": "visitas", "nombre": "visita", "bold": True, "como": "Ganancia del período ÷ visitas a la landing. La métrica más valiosa: resume todo lo que pasa después de la página. Su par es el costo por visita."},
                 {"key": "clics", "nombre": "clic"},
                 {"key": "unidades", "nombre": "lead", "bold": True, "como": "Ganancia del período ÷ registros. Su par es el CPL."},
                 {"key": "asist_vivo", "nombre": "asistente en vivo"},
                 {"key": "solicitudes", "nombre": "solicitud"},
                 {"key": "ventas_front", "nombre": "cliente", "bold": True, "como": "Ganancia del período ÷ compradores. Su par es el CPA."}],
    "embudo": [
        {"key": "impresiones", "label": "Impresiones del anuncio (por mil)", "mult": 1000, "nota": "Costo por mil impresiones (CPM) y CPM máximo. Palancas: público, frecuencia, horario."},
        {"key": "clics", "label": "Clics al enlace", "nota": "Costo por clic. Palanca: el creativo (CTR)."},
        {"key": "visitas", "label": "Visitas a la landing", "nota": "Costo por visita. Palanca: velocidad de carga, enlace correcto."},
        {"key": "unidades", "label": "Registros (leads)", "bold": True, "nota": "CPL real. Palanca: promesa y formulario del landing."},
        {"key": "registros_calif", "label": "Registros calificados", "vs": "unidades", "nota": "CPL calificado. Sobre registros."},
        {"key": "en_grupo", "label": "Entran al grupo de WhatsApp", "vs": "unidades", "nota": "Costo por persona en el grupo. Sobre registros."},
        {"key": "asist_vivo", "label": "Asisten en vivo", "vs": "unidades", "bold": True, "nota": "Costo por asistente en vivo. Sobre registros. Palancas: recordatorios, grupo, horario."},
        {"key": "asist_replay", "label": "Ven el replay", "vs": "unidades", "nota": "Costo por persona que vio el replay. Sobre registros."},
        {"key": "solic_vivo", "label": "Solicitan, de los que estuvieron en vivo", "vs": "asist_vivo", "nota": "Formulario de compra, aplicación o vendedor. Sobre asistentes en vivo. Palancas: oferta, pitch."},
        {"key": "solic_replay", "label": "Solicitan, de los que vieron el replay", "vs": "asist_replay", "nota": "Sobre los que vieron el replay."},
        {"key": "solicitudes", "label": "Solicitudes (total)", "vs": "unidades", "bold": True, "nota": "Costo por solicitud. Sobre registros."},
        {"key": "ventas_front", "label": "Compran la oferta", "vs": "solicitudes", "bold": True, "nota": "CPA: costo por comprador. Sobre solicitudes (cierre). Palancas: seguimiento, vendedor, forma de pago."},
        {"key": "ventas_bump", "label": "Toman el bump", "vs": "ventas_front", "costo": False, "techo": False, "nota": "Sobre compradores. Se pagó con el CPA; suma al AOV."},
        {"key": "ventas_backend", "label": "Pasan al programa superior", "vs": "ventas_front", "costo": False, "techo": False, "nota": "Sobre compradores."},
    ],
    "inicio": inicio("embudo de webinar gratuito: anuncios que llevan a una landing de registro, un grupo de WhatsApp, un webinar en vivo (con replay) donde se presenta una oferta, y un programa superior que se vende después",
                     ["La unidad que comprás es el registro (lead). El número que manda es el valor neto por registro contra el costo por registro (CPL real y CPL calificado). Después, escalón por escalón: costo por persona en el grupo, costo por asistente en vivo, costo por solicitud y cierre, cada uno con su cantidad y su porcentaje."],
                     ["Un lanzamiento semanal con 6.000 USD de pauta. CPM de 4,50, CTR del 2,2 %, el 90 % de los clics carga la landing y el 23 % se registra: CPL cerca de 1,00 y unos 6.000 registros.",
                      "El formulario califica: el 60 % de los registros califica, así que el CPL calificado ronda 1,65 contra un CPL real cerca de 1,00. El 67 % entra al grupo de WhatsApp (costo por persona en el grupo cerca de 1,50), el 15 % asiste en vivo (costo por asistente cerca de 6,60) y el 55 % ve el replay. Cuando se presenta la oferta, el 10 % de los asistentes en vivo solicita (completa el formulario de compra o de aplicación, o pide hablar con un vendedor) y el 2,5 % de los del replay; el 40 % de las solicitudes termina en compra: unas 70 ventas de una oferta de 297, con un bump de 47 (20 %) y un programa de 997 al que pasa el 5 %.",
                      "Costos: pasarela 10 %, reembolsos 5 %, 0,10 por registro en WhatsApp e IA, fijos 1.200 por lanzamiento. Cobranza 70 / 15 / 15 (hay cuotas).",
                      "Resultado: facturado cerca de 25.000 por lanzamiento, ROAS sobre cash neto de 3,5, techo de CPL cerca de 3,40 y objetivo cerca de 2,60: hay margen para escalar. Cambiá los números por los tuyos."],
                     "registro", "registros", "lanzamiento",
                     ["8. El techo de CPL supone que el show rate y la conversión se mantienen. Si el show rate cae, el techo cae con él: por eso el show rate se mira antes que el CPL cuando algo no cierra."]),
    "supuestos": [
        {"grupo": "1. Inversión y tráfico", "items": [
            {"key": "inversion", "label": "Inversión en publicidad por lanzamiento", "val": 6000, "fmt": "money0", "unidad": "USD / lanzamiento", "nota": "Un lanzamiento = un ciclo de captación + webinar + venta (en el ejemplo, una semana)."},
            {"key": "lanz_mes", "label": "Lanzamientos por mes (para la proyección)", "val": 4, "fmt": "int", "unidad": "lanzamientos / mes", "nota": "Cuántos lanzamientos como este hacés por mes. La proyección multiplica inversión, costos fijos y ventas por este número."},
            {"key": "cpm", "label": "CPM (costo por mil impresiones)", "esc": (6.0, 4.5, 3.5), "fmt": "money", "unidad": "USD", "nota": "Lo que cobra Meta por mil impresiones. Hispano: 3 a 7."},
            {"key": "ctr", "label": "CTR al enlace", "esc": (0.016, 0.022, 0.030), "fmt": "pct", "unidad": "%", "nota": "Clics en el enlace ÷ impresiones."},
            {"key": "clic_visita", "label": "% de clics que cargan la landing", "val": 0.90, "fmt": "pct", "unidad": "%", "nota": "Siempre menor a 100 %: una parte cierra antes de que cargue."},
        ]},
        {"grupo": "2. Landing de registro", "items": [
            {"key": "conv_landing", "label": "% de visitas que se registran", "esc": (0.18, 0.23, 0.30), "fmt": "pct", "unidad": "%", "nota": "La conversión del landing. Con nombre + WhatsApp: 20 a 30 %."},
            {"key": "calif_pct", "label": "% de registros que califican (si el formulario tiene una pregunta que califica)", "esc": (0.50, 0.60, 0.70), "fmt": "pct", "unidad": "%", "nota": "Si no calificás en el formulario, poné 100 %. Sirve para ver el CPL calificado además del CPL real."},
        ]},
        {"grupo": "3. Grupo de WhatsApp y asistencia", "items": [
            {"key": "grupo_pct", "label": "% de registrados que entran al grupo de WhatsApp", "esc": (0.55, 0.67, 0.78), "fmt": "pct", "unidad": "%", "nota": "Si no usás grupo, poné 0 %: no afecta las ventas en este modelo, solo el techo por persona en el grupo."},
            {"key": "show_vivo", "label": "% de registrados que asisten en vivo", "esc": (0.11, 0.15, 0.20), "fmt": "pct", "unidad": "%", "nota": "Tráfico frío hispano: 10 a 20 %. En B2B USA promedia 33 %."},
            {"key": "show_replay", "label": "% de registrados que ven el replay", "esc": (0.40, 0.55, 0.70), "fmt": "pct", "unidad": "%", "nota": "Sin contar a los que fueron en vivo."},
        ]},
        {"grupo": "4. Oferta y escalera", "items": [
            {"key": "precio_oferta", "label": "Oferta del webinar: precio", "val": 297, "fmt": "money", "unidad": "USD", "nota": "El producto que se presenta en el webinar."},
            {"key": "solic_vivo_pct", "label": "% de asistentes en vivo que solicitan (formulario de compra, de aplicación o hablar con un vendedor)", "esc": (0.06, 0.10, 0.15), "fmt": "pct", "unidad": "%", "nota": "La solicitud es lo que pasa en el webinar cuando se presenta la oferta. Incluye la ventana de 72 h."},
            {"key": "solic_replay_pct", "label": "% de los que ven el replay que solicitan", "esc": (0.012, 0.025, 0.04), "fmt": "pct", "unidad": "%", "nota": "Mucho menor que en vivo."},
            {"key": "cierre_pct", "label": "% de solicitudes que terminan en compra", "esc": (0.30, 0.40, 0.50), "fmt": "pct", "unidad": "%", "nota": "Con compra directa en el formulario suele ser alto; con vendedor o aplicación, 30 a 50 %."},
            {"key": "bump_precio", "label": "Bump en el checkout: precio", "val": 47, "fmt": "money", "unidad": "USD", "nota": "Oferta extra con una casilla en el checkout."},
            {"key": "bump_conv", "label": "Bump: % de compradores que lo toman", "esc": (0.12, 0.20, 0.30), "fmt": "pct", "unidad": "%", "nota": ""},
            {"key": "backend_precio", "label": "Programa superior: precio", "val": 997, "fmt": "money", "unidad": "USD", "nota": "Se vende después de la oferta, por llamada o por ascenso."},
            {"key": "backend_conv", "label": "Programa superior: % de compradores que lo toman", "esc": (0.03, 0.05, 0.08), "fmt": "pct", "unidad": "%", "nota": "Sobre compradores de la oferta."},
        ]},
        {"grupo": "5. Costos", "items": costos(0.10, 0.0, 0.05, 0.10, "registro", 1200, "lanzamiento",
                                                 "Sobre el cash cobrado. Si vendés el programa superior por llamada, poné acá la comisión del closer (10 a 15 % de esa parte).",
                                                 "WhatsApp API, email, IA: lo que pagás por cada registro.")},
        {"grupo": "6. Cobranza", "items": cobranza(0.70, 0.15, 0.15, "Con cuotas, el 70 % entra el primer mes y el resto en los dos siguientes.")},
        {"grupo": "7. Objetivos y proyección", "items": objetivos(2.0, 60, "ventas / lanzamiento", 5000, "lanzamiento")},
    ],
    "calculo": [
        {"seccion": "Tráfico y registros"},
        {"key": "impresiones", "label": "Impresiones", "f": "IF({cpm}=0,0,{inversion}/{cpm}*1000)", "fmt": "int", "como": "Inversión ÷ CPM × 1.000."},
        {"key": "clics", "label": "Clics al enlace", "f": "{impresiones}*{ctr}", "fmt": "int", "como": "Impresiones × CTR."},
        {"key": "visitas", "label": "Visitas a la landing", "f": "{clics}*{clic_visita}", "fmt": "int", "como": "Clics × % que carga."},
        {"key": "cpu", "label": "Costo por registro (CPL)", "f": "IF({ctr}*{clic_visita}*{conv_landing}=0,0,{cpm}/1000/({ctr}*{clic_visita}*{conv_landing}))", "fmt": "money", "como": "CPM ÷ 1.000 ÷ (CTR × clic→visita × conversión del landing).", "bold": True},
        {"key": "unidades", "label": "Registros (leads)", "f": "{inversion}/{cpu}", "fmt": "int", "como": "Inversión ÷ CPL.", "bold": True},
        {"key": "registros_calif", "label": "Registros calificados", "f": "{unidades}*{calif_pct}", "fmt": "int", "como": "Registros × % que califica."},
        {"key": "cpl_calif", "label": "Costo por registro calificado (CPL calificado)", "f": "{inversion}/{registros_calif}", "fmt": "money", "como": "Inversión ÷ registros calificados.", "bold": True},
        {"seccion": "Grupo y asistencia"},
        {"key": "en_grupo", "label": "Personas en el grupo de WhatsApp", "f": "{unidades}*{grupo_pct}", "fmt": "int", "como": "Registros × % que entra."},
        {"key": "costo_grupo", "label": "Costo por persona en el grupo", "f": "{inversion}/{en_grupo}", "fmt": "money", "como": "Inversión ÷ personas en el grupo.", "bold": True},
        {"key": "asist_vivo", "label": "Asistentes en vivo", "f": "{unidades}*{show_vivo}", "fmt": "int", "como": "Registros × show rate en vivo.", "bold": True},
        {"key": "asist_replay", "label": "Vieron el replay", "f": "{unidades}*{show_replay}", "fmt": "int", "como": "Registros × % que ve el replay."},
        {"key": "costo_asistente", "label": "Costo por asistente en vivo", "f": "{inversion}/{asist_vivo}", "fmt": "money", "como": "Inversión ÷ asistentes en vivo."},
        {"seccion": "Solicitudes (formulario de compra, aplicación o vendedor), ventas y facturación"},
        {"key": "solic_vivo", "label": "Solicitudes: en vivo", "f": "{asist_vivo}*{solic_vivo_pct}", "fmt": "num1", "como": "Asistentes en vivo × % que solicita."},
        {"key": "solic_replay", "label": "Solicitudes: replay", "f": "{asist_replay}*{solic_replay_pct}", "fmt": "num1", "como": "Replay × % que solicita."},
        {"key": "solicitudes", "label": "Solicitudes (total)", "f": "{solic_vivo}+{solic_replay}", "fmt": "num1", "como": "En vivo + replay.", "bold": True},
        {"key": "solic_sobre_leads", "label": "% de registros que solicitan", "f": "{solicitudes}/{unidades}", "fmt": "pct2", "como": "Solicitudes ÷ registros."},
        {"key": "costo_solicitud", "label": "Costo por solicitud", "f": "{inversion}/{solicitudes}", "fmt": "money", "como": "Inversión ÷ solicitudes.", "bold": True},
        {"key": "ventas_front", "label": "Ventas de la oferta", "f": "{solicitudes}*{cierre_pct}", "fmt": "num1", "como": "Solicitudes × % que termina en compra.", "bold": True},
        {"key": "conv_unidad_venta", "label": "% de registros que compran", "f": "{ventas_front}/{unidades}", "fmt": "pct2", "como": "Ventas ÷ registros."},
        {"key": "cpa", "label": "Costo por comprador (CPA)", "f": "{inversion}/{ventas_front}", "fmt": "money", "como": "Inversión ÷ ventas de la oferta.", "bold": True},
        {"key": "fact_front", "label": "Facturado: oferta", "f": "{ventas_front}*{precio_oferta}", "fmt": "money0", "como": "Ventas × precio."},
        {"key": "ventas_bump", "label": "Ventas: bump", "f": "{ventas_front}*{bump_conv}", "fmt": "num1", "como": "Compradores × % que lo toma."},
        {"key": "fact_bump", "label": "Facturado: bump", "f": "{ventas_bump}*{bump_precio}", "fmt": "money0", "como": "Ventas × precio."},
        {"key": "ventas_backend", "label": "Ventas: programa superior", "f": "{ventas_front}*{backend_conv}", "fmt": "num1", "como": "Compradores × % que asciende."},
        {"key": "fact_backend", "label": "Facturado: programa superior", "f": "{ventas_backend}*{backend_precio}", "fmt": "money0", "como": "Ventas × precio."},
        {"key": "facturado", "label": "Facturado total", "f": "{fact_front}+{fact_bump}+{fact_backend}", "fmt": "money0", "como": "Oferta + bump + programa.", "bold": True},
        {"key": "aov", "label": "Facturado por comprador (AOV)", "f": "{facturado}/{ventas_front}", "fmt": "money", "como": "Facturado ÷ ventas de la oferta.", "bold": True},
        {"key": "ventas_por_unidad", "label": "Ventas de la oferta por registro (para la proyección)", "f": "{ventas_front}/{unidades}", "fmt": "pct2", "como": "Igual a '% de registros que compran'."},
        {"key": "fact_por_unidad", "label": "Facturado por registro", "f": "{facturado}/{unidades}", "fmt": "money", "como": "Facturado ÷ registros."},
        *cash_rows("registro"),
        {"seccion": "Cuánto vale cada registro y hasta cuánto pagar"},
        {"key": "vpu", "label": "Valor neto por registro", "f": "({neto}-{semivar})/{unidades}", "fmt": "money", "como": "(Cash neto − costos por registro) ÷ registros.", "bold": True},
        {"key": "techo_cpu", "label": "Techo de CPL (break-even)", "f": "{vpu}", "fmt": "money", "como": "Igual al valor neto por registro.", "bold": True},
        {"key": "objetivo_cpu", "label": "Objetivo de CPL", "f": "{techo_cpu}/(1+{margen_seg})", "fmt": "money", "como": "Techo ÷ (1 + margen de seguridad).", "bold": True},
        {"key": "techo_grupo", "label": "Techo de costo por persona en el grupo", "f": "IF({grupo_pct}=0,0,{vpu}/{grupo_pct})", "fmt": "money", "como": "Valor por registro ÷ % que entra al grupo."},
        {"key": "techo_asistente", "label": "Techo de costo por asistente en vivo", "f": "{vpu}/{show_vivo}", "fmt": "money", "como": "Valor por registro ÷ show rate.", "bold": True},
        {"key": "techo_cpl_calif", "label": "Techo de CPL calificado", "f": "{vpu}/{calif_pct}", "fmt": "money", "como": "Valor por registro ÷ % que califica."},
        {"key": "techo_solicitud", "label": "Techo de costo por solicitud", "f": "{vpu}*{unidades}/{solicitudes}", "fmt": "money", "como": "Valor total ÷ solicitudes.", "bold": True},
        {"key": "techo_cpa", "label": "Techo de costo por comprador (CPA máximo)", "f": "{vpu}/{conv_unidad_venta}", "fmt": "money", "como": "Valor por registro ÷ % de registros que compran."},
        {"key": "objetivo_cpa", "label": "Objetivo de CPA", "f": "{techo_cpa}/(1+{margen_seg})", "fmt": "money", "como": "CPA máximo ÷ (1 + margen de seguridad)."},
        {"seccion": "Semáforo y cuánto invertir"},
        {"key": "semaforo", "label": "Semáforo del CPL actual", "f": 'IF({cpu}>{techo_cpu},"ROJO",IF(AND({cpu}<={objetivo_cpu},{roas_cash}>={roas_obj}),"VERDE","AMARILLO"))', "fmt": "txt", "como": "Rojo: costo > techo. Verde: costo ≤ objetivo y ROAS sobre cash neto ≥ objetivo. Amarillo: el resto.", "bold": True},
        {"key": "inv_meta", "label": "Inversión necesaria para la meta de ventas (al CPL actual)", "f": 'IF({conv_unidad_venta}=0,"inalcanzable con estos supuestos",{meta_ventas}/{conv_unidad_venta}*{cpu})', "fmt": "money0", "como": "Meta ÷ % de registros que compran × CPL.", "bold": True},
        {"key": "inv_meta_obj", "label": "Inversión para la meta al CPL objetivo (lo máximo que conviene pagar)", "f": 'IF({conv_unidad_venta}=0,"inalcanzable con estos supuestos",{meta_ventas}/{conv_unidad_venta}*{objetivo_cpu})', "fmt": "money0", "como": "Lo mismo, al CPL objetivo."},
    ],
    "resumen": [
        {"seccion": "Resultado del lanzamiento"},
        {"key": "profit", "que": "Cash neto menos costos y menos inversión."},
        {"key": "roas_cash", "que": "Cada dólar invertido vuelve como esto, ya neto."},
        {"key": "roas_fact", "que": "Sobre facturado. No decidas con este."},
        {"key": "unidades", "que": "Registros que compra la pauta."},
        {"key": "asist_vivo", "que": "Asistentes en vivo."},
        {"key": "ventas_front", "que": "Ventas de la oferta (vivo + replay)."},
        {"seccion": "Unit economics"},
        {"key": "cpu", "que": "CPL real: inversión ÷ registros."},
        {"key": "cpl_calif", "que": "CPL calificado: inversión ÷ registros que califican."},
        {"key": "costo_grupo", "que": "Lo que te cuesta cada persona que entra al grupo."},
        {"key": "vpu", "que": "Lo que vale un registro en cash neto."},
        {"key": "costo_asistente", "que": "Lo que te cuesta cada persona que asiste en vivo."},
        {"seccion": "Las dos caras de cada número"},
        {"key": "gan_visitas", "que": "Lo que te queda por cada visita a la landing. La métrica más valiosa del embudo."},
        {"key": "gan_clics", "que": "Lo que te queda por cada clic. Su par es el costo por clic (Embudo)."},
        {"key": "gan_unidades", "que": "Lo que te queda por cada registro. Su par es el CPL."},
        {"key": "gan_ventas_front", "que": "Lo que te queda por cada comprador. Su par es el CPA."},
        {"key": "aov", "label": "Order value (AOV)", "que": "Facturado por comprador con bump y programa."},
        {"key": "aov_neto", "label": "Order value neto (AOV neto)", "que": "Lo mismo después de comisiones, reembolsos y costos por registro."},
        {"key": "solicitudes", "que": "Formularios de compra, aplicaciones o pedidos de hablar con un vendedor."},
        {"key": "costo_solicitud", "que": "Lo que te cuesta cada solicitud."},
        {"key": "cpa", "que": "Lo que te cuesta cada comprador."},
        {"seccion": "Hasta cuánto pagar"},
        {"key": "techo_cpu", "que": "CPL donde no ganás ni perdés."},
        {"key": "objetivo_cpu", "que": "A este CPL o menos estás en verde."},
        {"key": "techo_asistente", "que": "Costo máximo por asistente en vivo."},
        {"key": "techo_solicitud", "que": "Costo máximo por solicitud."},
        {"key": "techo_cpa", "que": "CPA máximo si lo demás se mantiene."},
        {"key": "semaforo", "que": "Tu CPL actual contra techo y objetivo."},
        {"seccion": "Cuánto invertir y cuánta caja"},
        {"key": "inv_meta", "que": "Para la meta de ventas de Supuestos, al CPL actual."},
        {"key": "caja_necesaria", "label": "Caja que hay que tener (peor momento de la proyección)", "que": "Si da 0, el embudo se autofinancia: cada mes cobra más de lo que invierte."},
        {"key": "caja_minima", "label": "Saldo mínimo de caja con tu caja inicial", "que": "Si es negativo, la caja inicial no alcanza."},
        {"key": "profit_12m", "label": "Ganancia acumulada en 12 meses", "que": "Con la inversión creciendo según el supuesto."},
    ],
    "tablas": [
        {"titulo": "Precio de la oferta × % de solicitudes que terminan en compra → ganancia del lanzamiento", "nota": "A más precio, menos cierre: la tabla muestra qué combinación gana.",
         "fila_key": "precio_oferta", "fila_label": "Precio", "filas": [97, 197, 297, 497, 997], "fila_fmt": "money0",
         "col_key": "cierre_pct", "col_label": "% solicitud → compra", "cols": [0.25, 0.30, 0.40, 0.50, 0.60], "col_fmt": "pct", "salida": "profit", "salida_fmt": "money0"},
        {"titulo": "CPL × % de asistentes en vivo que solicitan → ganancia del lanzamiento", "nota": "La tabla del tráfico: hasta qué CPL seguís ganando según lo que mueve el webinar.",
         "fila_key": "cpu", "fila_label": "CPL", "filas": [0.5, 1.0, 1.5, 2.0, 3.0, 4.0, 6.0], "fila_fmt": "money",
         "col_key": "solic_vivo_pct", "col_label": "% en vivo que solicita", "cols": [0.05, 0.08, 0.10, 0.12, 0.15, 0.20], "col_fmt": "pct", "salida": "profit", "salida_fmt": "money0"},
    ],
    "tabla_roas": {"titulo": "Cuánto invertir para una facturación objetivo por lanzamiento, según el ROAS que querés", "nota": "Inversión = facturación ÷ ROAS. Debajo: cuántos registros hacen falta y cuánto podés pagar por cada uno.",
                   "facturacion": [5000, 10000, 20000, 30000, 50000], "roas": [1.5, 2.0, 2.5, 3.0, 4.0], "unidad_label": "Registros", "unidad_singular": "registro"},
    "palancas": [
        {"key": "cpm", "mult": 0.9, "label": "CPM 10 % más barato (público, frecuencia, horario)"},
        {"key": "ctr", "mult": 1.1, "label": "CTR 10 % más alto (mejor creativo)"},
        {"key": "conv_landing", "mult": 1.1, "label": "Landing 10 % más conversión"},
        {"key": "show_vivo", "mult": 1.1, "label": "Show rate en vivo 10 % más alto (recordatorios, grupo, horario)"},
        {"key": "solic_vivo_pct", "mult": 1.1, "label": "10 % más asistentes en vivo que solicitan (oferta, pitch)"},
        {"key": "cierre_pct", "mult": 1.1, "label": "10 % más solicitudes que terminan en compra (seguimiento, vendedor)"},
        {"key": "precio_oferta", "mult": 1.1, "label": "Precio de la oferta 10 % más alto (misma conversión)"},
        {"key": "bump_conv", "mult": 1.1, "label": "Bump tomado 10 % más"},
        {"key": "backend_conv", "mult": 1.1, "label": "Programa superior 10 % más tomado"},
    ],
    "seguimiento": {"periodo": "lanzamiento", "filas": [
        {"seccion": "Datos que cargás"},
        {"key": "inversion_r", "label": "Inversión en publicidad", "tipo": "in", "fmt": "money0", "ejemplo": [6000, 6500, 7200]},
        {"key": "leads_r", "label": "Registros", "tipo": "in", "fmt": "int", "ejemplo": [5900, 6100, 6300]},
        {"key": "calif_r", "label": "Registros calificados", "tipo": "in", "fmt": "int", "ejemplo": [3540, 3660, 3780]},
        {"key": "grupo_r", "label": "Entraron al grupo", "tipo": "in", "fmt": "int", "ejemplo": [3950, 4100, 4150]},
        {"key": "vivo_r", "label": "Asistentes en vivo", "tipo": "in", "fmt": "int", "ejemplo": [890, 900, 960]},
        {"key": "replay_r", "label": "Vieron el replay", "tipo": "in", "fmt": "int", "ejemplo": [3250, 3400, 3500]},
        {"key": "solic_r", "label": "Solicitudes (formulario de compra, aplicación o vendedor)", "tipo": "in", "fmt": "int", "ejemplo": [170, 165, 180]},
        {"key": "ventas_r", "label": "Ventas de la oferta", "tipo": "in", "fmt": "int", "ejemplo": [68, 66, 72]},
        {"key": "bump_r", "label": "Ventas del bump", "tipo": "in", "fmt": "int", "ejemplo": [14, 13, 15]},
        {"key": "backend_r", "label": "Ventas del programa superior", "tipo": "in", "fmt": "int", "ejemplo": [3, 4, 3]},
        {"key": "fact_r", "label": "Facturado del lanzamiento (a precio de lista, con cuotas por cobrar)", "tipo": "in", "fmt": "money0", "ejemplo": [23800, 23400, 25500]},
        {"key": "cash_r", "label": "Cash cobrado hasta ahora de ese lanzamiento", "tipo": "in", "fmt": "money0", "ejemplo": [16700, 16400, 17900]},
        {"seccion": "Lo que calcula el modelo"},
        {"key": "cpu_r", "label": "CPL real", "tipo": "f", "f": "{inversion_r}/{leads_r}", "fmt": "money", "bold": True},
        {"key": "grupo_pct_r", "label": "% registro → grupo", "tipo": "f", "f": "{grupo_r}/{leads_r}", "fmt": "pct"},
        {"key": "show_r", "label": "% registro → en vivo", "tipo": "f", "f": "{vivo_r}/{leads_r}", "fmt": "pct"},
        {"key": "conv_vivo_r", "label": "Ventas ÷ asistentes en vivo", "tipo": "f", "f": "{ventas_r}/{vivo_r}", "fmt": "pct"},
        {"key": "conv_lead_r", "label": "% registro → compra", "tipo": "f", "f": "{ventas_r}/{leads_r}", "fmt": "pct2"},
        {"key": "cpa_r", "label": "CPA real", "tipo": "f", "f": "{inversion_r}/{ventas_r}", "fmt": "money"},
        {"key": "costo_asist_r", "label": "Costo por asistente en vivo", "tipo": "f", "f": "{inversion_r}/{vivo_r}", "fmt": "money"},
        {"key": "cpl_calif_r", "label": "CPL calificado", "tipo": "f", "f": "{inversion_r}/{calif_r}", "fmt": "money"},
        {"key": "costo_grupo_r", "label": "Costo por persona en el grupo", "tipo": "f", "f": "{inversion_r}/{grupo_r}", "fmt": "money"},
        {"key": "solic_pct_r", "label": "% en vivo → solicitud", "tipo": "f", "f": "{solic_r}/{vivo_r}", "fmt": "pct"},
        {"key": "costo_solic_r", "label": "Costo por solicitud", "tipo": "f", "f": "{inversion_r}/{solic_r}", "fmt": "money", "bold": True},
        {"key": "cierre_r", "label": "% solicitud → compra", "tipo": "f", "f": "{ventas_r}/{solic_r}", "fmt": "pct"},
        *seguimiento_calc("inversion_r", "leads_r", "fact_r", "cash_r"),
    ]},
    "benchmarks": [
        {"metrica": "CPL (USD)", "niveles": [">3,00", "1,50 a 3,00", "0,80 a 1,50", "<0,80"], "key": "cpu", "fuente": "Webinars gratuitos hispanos a tráfico frío, 2025 a 2026. Un agregador LATAM cita 0,50 a 3 para webinar (fuente débil)."},
        {"metrica": "% visitas → registro (landing)", "niveles": ["<15 %", "15 a 22 %", "22 a 30 %", ">30 %"], "key": "conv_landing", "fuente": "Con nombre + WhatsApp. Con solo email sube."},
        {"metrica": "% registro → grupo de WhatsApp", "niveles": ["<50 %", "50 a 65 %", "65 a 80 %", ">80 %"], "key": "grupo_pct", "fuente": "Depende de cuán directo sea el botón al grupo."},
        {"metrica": "% registro → en vivo", "niveles": ["<10 %", "10 a 15 %", "15 a 22 %", ">22 %"], "key": "show_vivo", "fuente": "Hispano tráfico frío. En B2B USA el promedio es 33 % (Goldcast 2025, 19.531 webinars)."},
        {"metrica": "% registro → replay", "niveles": ["<40 %", "40 a 60 %", "60 a 80 %", ">80 %"], "key": "show_replay", "fuente": "Con bot de WhatsApp que manda el replay."},
        {"metrica": "% registros que califican", "niveles": ["<40 %", "40 a 55 %", "55 a 70 %", ">70 %"], "key": "calif_pct", "fuente": "Depende de la pregunta que califica."},
        {"metrica": "Costo por persona en el grupo (USD)", "niveles": [">3,00", "1,80 a 3,00", "1,00 a 1,80", "<1,00"], "key": "costo_grupo", "fuente": "Webinars hispanos 2026: mediana cerca de 1,60."},
        {"metrica": "% asistentes en vivo que solicitan", "niveles": ["<5 %", "5 a 10 %", "10 a 15 %", ">15 %"], "key": "solic_vivo_pct", "fuente": "Formulario de compra o aplicación presentado en el webinar. Hispano: 10 a 15 % de los asistentes en vivo."},
        {"metrica": "Costo por solicitud (USD)", "niveles": [">150", "80 a 150", "40 a 80", "<40"], "key": "costo_solicitud", "fuente": "Webinars de llamada hispanos: mediana cerca de 80."},
        {"metrica": "% solicitud → compra", "niveles": ["<25 %", "25 a 40 %", "40 a 55 %", ">55 %"], "key": "cierre_pct", "fuente": "Con vendedor: 40 a 60 %. Compra directa en el formulario: más alto."},
        {"metrica": "% registro → compra", "niveles": ["<0,6 %", "0,6 a 1 %", "1 a 1,5 %", ">1,5 %"], "key": "conv_unidad_venta", "fuente": "El producto de todas las conversiones."},
        {"metrica": "Costo por asistente en vivo (USD)", "niveles": [">15", "8 a 15", "5 a 8", "<5"], "key": "costo_asistente", "fuente": ""},
        {"metrica": "ROAS sobre cash neto", "niveles": ["<1,2", "1,2 a 1,8", "1,8 a 2,5", ">2,5"], "key": "roas_cash", "fuente": "Por lanzamiento, cobranza completa."},
    ],
    "glosario": GLOSARIO_BASE + [("Replay", "La grabación del webinar que ven los que no fueron en vivo. Convierte mucho menos.", "Supuestos"),
                                 ("Ventana de 72 h", "Los tres días después del webinar en que la oferta sigue abierta. Sus solicitudes se cuentan dentro de las de en vivo o replay.", "Supuestos"),
                                 ("Solicitud", "Lo que hace el asistente cuando se presenta la oferta: completa el formulario de compra, la aplicación, o pide hablar con un vendedor. Se mide en cantidad, costo por solicitud y % sobre asistentes en vivo.", "Modelo, Seguimiento"),
                                 ("Registro calificado", "Registro que pasa la pregunta que califica en el formulario. Da el CPL calificado, además del CPL real.", "Modelo")],
    "chequeos": chequeos_base(["ctr", "clic_visita", "conv_landing", "calif_pct", "grupo_pct", "show_vivo", "show_replay", "solic_vivo_pct", "solic_replay_pct", "cierre_pct", "bump_conv", "backend_conv"],
                              [("unidades", "en_grupo"), ("unidades", "asist_vivo"), ("asist_vivo", "solic_vivo"), ("asist_replay", "solic_replay"), ("solicitudes", "ventas_front")],
                              positivos=["cpm", "ctr", "clic_visita", "conv_landing"],
                              extra=[{"label": "En vivo + replay no superan el 100 % de los registrados", "cond": "({show_vivo}+{show_replay})<=1", "ayuda": "El replay se cuenta sin los que fueron en vivo."}]),
}
