"""Especificaciones: (3) embudo de llamada, (4) webinar pago."""
from mf_comun import inicio, GLOSARIO_BASE, chequeos_base, cobranza, objetivos, costos, cash_rows, seguimiento_calc

# ---------------------------------------------------------------- 3. EMBUDO DE LLAMADA
LLAMADA = {
    "archivo": "03_Modelo_Financiero_Embudo_de_Llamada.xlsx",
    "titulo": "Modelo financiero · Embudo de llamada (high ticket)",
    "subtitulo": "Anuncios → página con VSL (o webinar previo) → aplicación → agenda → llamada → cierre → cash en cuotas",
    "unidad_singular": "lead", "unidad_plural": "leads",
    "ganancia": [{"key": "visitas", "nombre": "visita", "bold": True, "como": "Ganancia del período ÷ visitas a la página. La métrica más valiosa: resume todo lo que pasa después. Su par es el costo por visita."},
                 {"key": "clics", "nombre": "clic"},
                 {"key": "unidades", "nombre": "lead", "bold": True, "como": "Ganancia del período ÷ leads. Su par es el CPL."},
                 {"key": "agendas", "nombre": "agenda"},
                 {"key": "llamadas", "nombre": "llamada"},
                 {"key": "ventas_front", "nombre": "cliente", "bold": True, "como": "Ganancia del período ÷ compradores. Su par es el CAC."}],
    "embudo": [
        {"key": "impresiones", "label": "Impresiones del anuncio (por mil)", "mult": 1000, "nota": "Costo por mil impresiones (CPM) y CPM máximo."},
        {"key": "clics", "label": "Clics al enlace", "nota": "Costo por clic (CTR)."},
        {"key": "visitas", "label": "Visitas a la página", "nota": "Costo por visita."},
        {"key": "unidades", "label": "Leads", "bold": True, "nota": "CPL real."},
        {"key": "asistentes", "label": "Asisten al evento previo (si hay)", "vs": "unidades", "nota": "Solo cuenta con el interruptor de evento en 1; si no, queda en 0."},
        {"key": "aplicaciones", "label": "Completan la aplicación", "vs": "unidades", "nota": "Costo por aplicación. Sobre leads (sobre asistentes si hay evento)."},
        {"key": "calificados", "label": "Califican", "vs": "aplicaciones", "nota": "Sobre aplicaciones. Palanca: las preguntas del formulario."},
        {"key": "agendas", "label": "Agendan la llamada", "vs": "calificados", "bold": True, "nota": "Costo por agenda. Sobre calificados. Palancas: setter, confirmación por WhatsApp."},
        {"key": "llamadas", "label": "Aparecen en la llamada (show)", "vs": "agendas", "nota": "Costo por llamada realizada. Sobre agendas. Palancas: recordatorio, video de bienvenida."},
        {"key": "ventas_front", "label": "Compran el programa", "vs": "llamadas", "bold": True, "nota": "CAC. Sobre llamadas (cierre). Juzgar con 3 a 4 eventos, nunca con uno."},
        {"key": "ventas_ds", "label": "Toman el downsell", "vs": "llamadas", "costo": False, "techo": False, "nota": "Sobre llamadas que no compraron. Se pagó con el CAC; suma al facturado."},
    ],
    "inicio": inicio("embudo de llamada: anuncios que captan leads, una página con video o un webinar que los lleva a aplicar, una agenda, una llamada con un closer y una venta de ticket alto que se cobra al contado o en cuotas",
                     ["La unidad que comprás es el lead. El número que manda es el costo por agenda contra lo que vale una agenda, y después el cierre. Con ticket alto una venta más o menos cambia el ROAS de un mes: juzgá por ventanas de 3 a 4 eventos, nunca por uno."],
                     ["Un programa de 1.500 USD vendido por llamada. Se invierten 4.500 USD por mes a CPM 10 y CTR 1,5 %; el 85 % de los clics carga la página y el 28 % deja sus datos: CPL cerca de 2,80 y unos 1.600 leads.",
                      "Sin evento previo (interruptor en 0): el 10 % de los leads completa la aplicación, el 60 % califica, el 60 % de los calificados agenda, el 70 % aparece en la llamada y el 25 % compra: unas 10 ventas por mes. A los que no compran se les ofrece un downsell de 497 que toma el 10 %.",
                      "Si tenés un webinar antes de la aplicación, poné el interruptor en 1 y el % de asistencia: la aplicación pasa a medirse sobre asistentes.",
                      "Costos: pasarela 5 %, closers 10 % del cash cobrado, reembolsos 5 %, 0,20 por lead en WhatsApp y setter, fijos 2.500 por mes. Cobranza 60 / 20 / 20: el facturado se cobra en tres meses.",
                      "Resultado: facturado cerca de 17.000 por mes y ROAS sobre cash neto de 3 con la cobranza completa, pero solo 1,8 con lo que entra el primer mes. En este ejemplo el embudo se autofinancia (la caja necesaria da 0): subí el crecimiento mensual o bajá la cobranza del mes 1 en Supuestos y vas a ver en qué mes la caja empieza a hacer falta. El techo de CPL queda cerca de 8: el tráfico no es el cuello de botella, el cierre sí."],
                     "lead", "leads", "mes",
                     ["8. En llamada, el techo de CPL casi nunca es el problema: lo que mata el mes es un cierre bajo o un show de llamadas bajo. Mirá primero % de agenda, show de la llamada y cierre; el CPL al final.",
                      "9. Facturado no es cash. Con cuotas, el ROAS sobre facturado puede dar 3 mientras la caja del mes queda en rojo. Decidí con cash neto y mirá la caja mínima de Proyección."]),
    "supuestos": [
        {"grupo": "1. Inversión y tráfico", "items": [
            {"key": "inversion", "label": "Inversión en publicidad por mes", "val": 4500, "fmt": "money0", "unidad": "USD / mes", "nota": "150 USD por día en el ejemplo."},
            {"key": "cpm", "label": "CPM (costo por mil impresiones)", "esc": (14.0, 10.0, 7.0), "fmt": "money", "unidad": "USD", "nota": "Públicos de ticket alto suelen ser más caros: 7 a 15."},
            {"key": "ctr", "label": "CTR al enlace", "esc": (0.012, 0.015, 0.020), "fmt": "pct", "unidad": "%", "nota": ""},
            {"key": "clic_visita", "label": "% de clics que cargan la página", "val": 0.85, "fmt": "pct", "unidad": "%", "nota": ""},
        ]},
        {"grupo": "2. Página de captación", "items": [
            {"key": "conv_landing", "label": "% de visitas que dejan sus datos (lead)", "esc": (0.20, 0.28, 0.35), "fmt": "pct", "unidad": "%", "nota": "Registro al webinar o inicio de la aplicación."},
        ]},
        {"grupo": "3. Evento previo (opcional)", "items": [
            {"key": "hay_evento", "label": "¿Hay webinar o evento antes de la aplicación? (1 = sí, 0 = no)", "val": 0, "fmt": "int", "unidad": "1 / 0", "nota": "Con 1, la aplicación se mide sobre los asistentes; con 0, sobre todos los leads."},
            {"key": "show_evento", "label": "% de leads que asisten al evento", "esc": (0.10, 0.14, 0.20), "fmt": "pct", "unidad": "%", "nota": "Solo cuenta si el interruptor está en 1."},
        ]},
        {"grupo": "4. Aplicación, agenda y llamada", "items": [
            {"key": "aplic_pct", "label": "% que completa la aplicación (de leads, o de asistentes si hay evento)", "esc": (0.07, 0.10, 0.15), "fmt": "pct", "unidad": "%", "nota": "Formulario largo con preguntas que califican."},
            {"key": "calif_pct", "label": "% de aplicaciones que califican", "esc": (0.50, 0.60, 0.70), "fmt": "pct", "unidad": "%", "nota": "Pasan el filtro de capacidad de inversión y perfil."},
            {"key": "agenda_pct", "label": "% de calificados que agendan", "esc": (0.45, 0.60, 0.75), "fmt": "pct", "unidad": "%", "nota": "Mercado: 30 a 60 % de las aplicaciones terminan en agenda."},
            {"key": "show_llamada", "label": "% de agendas que aparecen en la llamada", "esc": (0.60, 0.70, 0.80), "fmt": "pct", "unidad": "%", "nota": "Mercado: 65 a 75 %. Confirmación por WhatsApp y video de bienvenida lo suben."},
            {"key": "cierre", "label": "% de llamadas que compran", "esc": (0.18, 0.25, 0.35), "fmt": "pct", "unidad": "%", "nota": "Lead tibio y calificado: 20 a 40 %. Frío sin filtro: menos de 5 %."},
        ]},
        {"grupo": "5. Oferta", "items": [
            {"key": "ticket", "label": "Programa: precio", "val": 1500, "fmt": "money", "unidad": "USD", "nota": "Debajo de 1.500 un closer 1 a 1 rara vez se paga; el modelo te lo muestra en la ganancia."},
            {"key": "ds_precio", "label": "Downsell para quien no compra en la llamada: precio", "val": 497, "fmt": "money", "unidad": "USD", "nota": "Versión reducida o self-serve."},
            {"key": "ds_conv", "label": "Downsell: % de los que no compraron que lo toman", "esc": (0.05, 0.10, 0.15), "fmt": "pct", "unidad": "%", "nota": ""},
        ]},
        {"grupo": "6. Costos", "items": costos(0.05, 0.10, 0.05, 0.20, "lead", 2500, "mes",
                                                 "Comisión de closers y setters sobre el cash cobrado. 10 a 15 % es lo común.",
                                                 "WhatsApp, herramientas de agenda, setter por contacto.")},
        {"grupo": "7. Cobranza", "items": cobranza(0.60, 0.20, 0.20, "Ticket alto con cuotas: 60 % al contado o primera cuota, el resto en dos meses.")},
        {"grupo": "8. Objetivos y proyección", "items": objetivos(2.5, 15, "ventas / mes", 8000, "mes")},
    ],
    "calculo": [
        {"seccion": "Tráfico y leads"},
        {"key": "impresiones", "label": "Impresiones", "f": "IF({cpm}=0,0,{inversion}/{cpm}*1000)", "fmt": "int", "como": "Inversión ÷ CPM × 1.000."},
        {"key": "clics", "label": "Clics al enlace", "f": "{impresiones}*{ctr}", "fmt": "int", "como": "Impresiones × CTR."},
        {"key": "visitas", "label": "Visitas a la página", "f": "{clics}*{clic_visita}", "fmt": "int", "como": "Clics × % que carga."},
        {"key": "cpu", "label": "Costo por lead (CPL)", "f": "IF({ctr}*{clic_visita}*{conv_landing}=0,0,{cpm}/1000/({ctr}*{clic_visita}*{conv_landing}))", "fmt": "money", "como": "CPM ÷ 1.000 ÷ (CTR × clic→visita × conversión de la página).", "bold": True},
        {"key": "unidades", "label": "Leads", "f": "{inversion}/{cpu}", "fmt": "int", "como": "Inversión ÷ CPL.", "bold": True},
        {"seccion": "Evento, aplicación y agenda"},
        {"key": "asistentes", "label": "Asistentes al evento (si hay)", "f": "IF({hay_evento}=1,{unidades}*{show_evento},0)", "fmt": "int", "como": "Leads × asistencia, solo con el interruptor en 1."},
        {"key": "base_aplic", "label": "Base de la aplicación (asistentes o leads)", "f": "IF({hay_evento}=1,{asistentes},{unidades})", "fmt": "int", "como": "Sobre quién se mide la aplicación."},
        {"key": "aplicaciones", "label": "Aplicaciones completas", "f": "{base_aplic}*{aplic_pct}", "fmt": "int", "como": "Base × % que aplica."},
        {"key": "calificados", "label": "Calificados", "f": "{aplicaciones}*{calif_pct}", "fmt": "int", "como": "Aplicaciones × % que califica."},
        {"key": "agendas", "label": "Agendas", "f": "{calificados}*{agenda_pct}", "fmt": "num1", "como": "Calificados × % que agenda.", "bold": True},
        {"key": "llamadas", "label": "Llamadas realizadas", "f": "{agendas}*{show_llamada}", "fmt": "num1", "como": "Agendas × show de la llamada."},
        {"key": "costo_aplic", "label": "Costo por aplicación", "f": "{inversion}/{aplicaciones}", "fmt": "money", "como": "Inversión ÷ aplicaciones."},
        {"key": "costo_agenda", "label": "Costo por agenda", "f": "{inversion}/{agendas}", "fmt": "money", "como": "Inversión ÷ agendas.", "bold": True},
        {"key": "costo_llamada", "label": "Costo por llamada realizada", "f": "{inversion}/{llamadas}", "fmt": "money", "como": "Inversión ÷ llamadas."},
        {"seccion": "Ventas y facturación"},
        {"key": "ventas_front", "label": "Ventas del programa", "f": "{llamadas}*{cierre}", "fmt": "num1", "como": "Llamadas × cierre.", "bold": True},
        {"key": "ventas_ds", "label": "Ventas del downsell", "f": "({llamadas}-{ventas_front})*{ds_conv}", "fmt": "num1", "como": "(Llamadas − ventas) × % que toma el downsell."},
        {"key": "conv_unidad_venta", "label": "% de leads que compran el programa", "f": "{ventas_front}/{unidades}", "fmt": "pct2", "como": "Ventas ÷ leads."},
        {"key": "cpa", "label": "Costo por venta del programa (CAC)", "f": "{inversion}/{ventas_front}", "fmt": "money", "como": "Inversión ÷ ventas.", "bold": True},
        {"key": "fact_front", "label": "Facturado: programa", "f": "{ventas_front}*{ticket}", "fmt": "money0", "como": "Ventas × precio."},
        {"key": "fact_ds", "label": "Facturado: downsell", "f": "{ventas_ds}*{ds_precio}", "fmt": "money0", "como": "Ventas × precio."},
        {"key": "facturado", "label": "Facturado total", "f": "{fact_front}+{fact_ds}", "fmt": "money0", "como": "Programa + downsell.", "bold": True},
        {"key": "aov", "label": "Facturado por comprador del programa", "f": "{facturado}/{ventas_front}", "fmt": "money", "como": "Facturado ÷ ventas del programa."},
        {"key": "ventas_por_unidad", "label": "Ventas del programa por lead (para la proyección)", "f": "{ventas_front}/{unidades}", "fmt": "pct2", "como": "Igual a '% de leads que compran'."},
        {"key": "fact_por_unidad", "label": "Facturado por lead", "f": "{facturado}/{unidades}", "fmt": "money", "como": "Facturado ÷ leads."},
        *cash_rows("lead"),
        {"key": "roas_cash_m1", "label": "ROAS del cash del primer mes (sin cuotas futuras)", "f": "{cash_m1}*(1-{pasarela}-{closers}-{reembolsos})/{inversion}", "fmt": "ratio", "como": "Lo que vuelve el mismo mes. Si es menor a 1, el mes se financia con caja.", "bold": True},
        {"seccion": "Cuánto vale cada lead y hasta cuánto pagar"},
        {"key": "vpu", "label": "Valor neto por lead", "f": "({neto}-{semivar})/{unidades}", "fmt": "money", "como": "(Cash neto − costos por lead) ÷ leads.", "bold": True},
        {"key": "techo_cpu", "label": "Techo de CPL (break-even)", "f": "{vpu}", "fmt": "money", "como": "Igual al valor neto por lead.", "bold": True},
        {"key": "objetivo_cpu", "label": "Objetivo de CPL", "f": "{techo_cpu}/(1+{margen_seg})", "fmt": "money", "como": "Techo ÷ (1 + margen de seguridad).", "bold": True},
        {"key": "techo_aplic", "label": "Techo de costo por aplicación", "f": "{vpu}*{unidades}/{aplicaciones}", "fmt": "money", "como": "Valor total ÷ aplicaciones."},
        {"key": "techo_agenda", "label": "Techo de costo por agenda", "f": "{vpu}*{unidades}/{agendas}", "fmt": "money", "como": "Valor total ÷ agendas.", "bold": True},
        {"key": "techo_llamada", "label": "Techo de costo por llamada realizada", "f": "{vpu}*{unidades}/{llamadas}", "fmt": "money", "como": "Valor total ÷ llamadas."},
        {"key": "techo_cpa", "label": "Techo de costo por venta (CAC máximo)", "f": "{vpu}/{conv_unidad_venta}", "fmt": "money", "como": "Valor por lead ÷ % de leads que compran."},
        {"key": "objetivo_cpa", "label": "Objetivo de CAC", "f": "{techo_cpa}/(1+{margen_seg})", "fmt": "money", "como": "CAC máximo ÷ (1 + margen de seguridad)."},
        {"seccion": "Semáforo y cuánto invertir"},
        {"key": "semaforo", "label": "Semáforo del CPL actual", "f": 'IF({cpu}>{techo_cpu},"ROJO",IF(AND({cpu}<={objetivo_cpu},{roas_cash}>={roas_obj}),"VERDE","AMARILLO"))', "fmt": "txt", "como": "Rojo: costo > techo. Verde: costo ≤ objetivo y ROAS sobre cash neto ≥ objetivo. Amarillo: el resto.", "bold": True},
        {"key": "inv_meta", "label": "Inversión necesaria para la meta de ventas (al CPL actual)", "f": 'IF({conv_unidad_venta}=0,"inalcanzable con estos supuestos",{meta_ventas}/{conv_unidad_venta}*{cpu})', "fmt": "money0", "como": "Meta ÷ % de leads que compran × CPL.", "bold": True},
        {"key": "inv_meta_obj", "label": "Inversión para la meta al CPL objetivo (lo máximo que conviene pagar)", "f": 'IF({conv_unidad_venta}=0,"inalcanzable con estos supuestos",{meta_ventas}/{conv_unidad_venta}*{objetivo_cpu})', "fmt": "money0", "como": "Lo mismo, al CPL objetivo."},
        {"key": "llamadas_meta", "label": "Llamadas que hay que atender por mes para esa meta", "f": 'IF({cierre}=0,"inalcanzable con estos supuestos",{meta_ventas}/{cierre})', "fmt": "num1", "como": "Meta ÷ cierre. Sirve para dimensionar closers."},
    ],
    "resumen": [
        {"seccion": "Resultado del mes"},
        {"key": "profit", "que": "Cash neto (cobranza completa) menos costos y menos inversión."},
        {"key": "roas_cash", "que": "Sobre cash neto con la cobranza completa."},
        {"key": "roas_cash_m1", "que": "Solo con lo que entra el primer mes. Si es menor a 1, el mes se financia con caja."},
        {"key": "ventas_front", "que": "Ventas del programa por mes."},
        {"key": "facturado", "que": "A precio de lista, incluidas las cuotas por cobrar."},
        {"seccion": "La cadena"},
        {"key": "unidades", "que": "Leads que compra la pauta."},
        {"key": "agendas", "que": "Llamadas agendadas."},
        {"key": "llamadas", "que": "Llamadas que ocurren."},
        {"key": "costo_agenda", "que": "Lo que te cuesta cada agenda."},
        {"key": "cpa", "que": "Lo que te cuesta cada venta (CAC)."},
        {"seccion": "Las dos caras de cada número"},
        {"key": "gan_visitas", "que": "Lo que te queda por cada visita a la página. La métrica más valiosa del embudo."},
        {"key": "gan_clics", "que": "Lo que te queda por cada clic. Su par es el costo por clic (Embudo)."},
        {"key": "gan_unidades", "que": "Lo que te queda por cada lead. Su par es el CPL."},
        {"key": "gan_agendas", "que": "Lo que te queda por cada agenda. Su par es el costo por agenda."},
        {"key": "gan_ventas_front", "que": "Lo que te queda por cada cliente. Su par es el CAC."},
        {"key": "aov", "label": "Order value (AOV)", "que": "Facturado por comprador del programa, con el downsell."},
        {"key": "aov_neto", "label": "Order value neto (AOV neto)", "que": "Lo mismo después de comisiones, reembolsos y costos por lead."},
        {"seccion": "Hasta cuánto pagar"},
        {"key": "techo_cpu", "que": "CPL donde no ganás ni perdés."},
        {"key": "objetivo_cpu", "que": "A este CPL o menos estás en verde."},
        {"key": "techo_agenda", "que": "Costo máximo por agenda."},
        {"key": "techo_cpa", "que": "CAC máximo si lo demás se mantiene."},
        {"key": "semaforo", "que": "Tu CPL actual contra techo y objetivo."},
        {"seccion": "Cuánto invertir y cuánta caja"},
        {"key": "inv_meta", "que": "Para la meta de ventas de Supuestos, al CPL actual."},
        {"key": "llamadas_meta", "que": "Para dimensionar el equipo de closers."},
        {"key": "caja_necesaria", "label": "Caja que hay que tener (peor momento de la proyección)", "que": "Si da 0, el embudo se autofinancia: cada mes cobra más de lo que invierte."},
        {"key": "caja_minima", "label": "Saldo mínimo de caja con tu caja inicial", "que": "Si es negativo, la caja inicial no alcanza."},
        {"key": "profit_12m", "label": "Ganancia acumulada en 12 meses", "que": "Con la inversión creciendo según el supuesto."},
    ],
    "tablas": [
        {"titulo": "Precio del programa × % de llamadas que compran → ganancia del mes", "nota": "A más precio, menos cierre: la tabla muestra desde qué ticket el closer se paga.",
         "fila_key": "ticket", "fila_label": "Precio", "filas": [497, 997, 1500, 2500, 3500, 5000], "fila_fmt": "money0",
         "col_key": "cierre", "col_label": "% cierre", "cols": [0.15, 0.20, 0.25, 0.30, 0.35, 0.40], "col_fmt": "pct", "salida": "profit", "salida_fmt": "money0"},
        {"titulo": "CPL × % de llamadas que compran → ganancia del mes", "nota": "Hasta qué CPL seguís ganando según el cierre.",
         "fila_key": "cpu", "fila_label": "CPL", "filas": [1.0, 2.0, 3.0, 4.0, 6.0, 8.0, 12.0], "fila_fmt": "money",
         "col_key": "cierre", "col_label": "% cierre", "cols": [0.15, 0.20, 0.25, 0.30, 0.35, 0.40], "col_fmt": "pct", "salida": "profit", "salida_fmt": "money0"},
    ],
    "tabla_roas": {"titulo": "Cuánto invertir para una facturación objetivo por mes, según el ROAS que querés", "nota": "Inversión = facturación ÷ ROAS. Debajo: cuántos leads hacen falta y cuánto podés pagar por cada uno.",
                   "facturacion": [20000, 50000, 100000, 200000, 500000], "roas": [2.0, 3.0, 4.0, 5.0, 6.0], "unidad_label": "Leads", "unidad_singular": "lead"},
    "palancas": [
        {"key": "cpm", "mult": 0.9, "label": "CPM 10 % más barato"},
        {"key": "conv_landing", "mult": 1.1, "label": "Página 10 % más conversión a lead"},
        {"key": "aplic_pct", "mult": 1.1, "label": "10 % más aplicaciones"},
        {"key": "agenda_pct", "mult": 1.1, "label": "10 % más calificados que agendan"},
        {"key": "show_llamada", "mult": 1.1, "label": "Show de la llamada 10 % más alto"},
        {"key": "cierre", "mult": 1.1, "label": "Cierre 10 % más alto"},
        {"key": "ticket", "mult": 1.1, "label": "Precio 10 % más alto (mismo cierre)"},
        {"key": "closers", "mult": 0.9, "label": "Comisión de closers 10 % más baja"},
    ],
    "seguimiento": {"periodo": "mes", "filas": [
        {"seccion": "Datos que cargás"},
        {"key": "inversion_r", "label": "Inversión en publicidad", "tipo": "in", "fmt": "money0", "ejemplo": [4500, 4800, 5200]},
        {"key": "leads_r", "label": "Leads", "tipo": "in", "fmt": "int", "ejemplo": [1600, 1650, 1900]},
        {"key": "aplic_r", "label": "Aplicaciones completas", "tipo": "in", "fmt": "int", "ejemplo": [160, 155, 190]},
        {"key": "calif_r", "label": "Calificados", "tipo": "in", "fmt": "int", "ejemplo": [96, 90, 115]},
        {"key": "agendas_r", "label": "Agendas", "tipo": "in", "fmt": "int", "ejemplo": [58, 52, 70]},
        {"key": "llamadas_r", "label": "Llamadas realizadas", "tipo": "in", "fmt": "int", "ejemplo": [41, 35, 50]},
        {"key": "ventas_r", "label": "Ventas del programa", "tipo": "in", "fmt": "int", "ejemplo": [10, 8, 13]},
        {"key": "ds_r", "label": "Ventas del downsell", "tipo": "in", "fmt": "int", "ejemplo": [3, 3, 4]},
        {"key": "fact_r", "label": "Facturado del mes (a precio de lista, con cuotas por cobrar)", "tipo": "in", "fmt": "money0", "ejemplo": [16500, 13500, 21000]},
        {"key": "cash_r", "label": "Cash cobrado en el mes (incluye cuotas de meses anteriores)", "tipo": "in", "fmt": "money0", "ejemplo": [9000, 11500, 15000]},
        {"seccion": "Lo que calcula el modelo"},
        {"key": "cpu_r", "label": "CPL real", "tipo": "f", "f": "{inversion_r}/{leads_r}", "fmt": "money", "bold": True},
        {"key": "aplic_pct_r", "label": "% lead → aplicación", "tipo": "f", "f": "{aplic_r}/{leads_r}", "fmt": "pct"},
        {"key": "agenda_pct_r", "label": "% calificado → agenda", "tipo": "f", "f": "{agendas_r}/{calif_r}", "fmt": "pct"},
        {"key": "show_r", "label": "% agenda → llamada (show)", "tipo": "f", "f": "{llamadas_r}/{agendas_r}", "fmt": "pct"},
        {"key": "cierre_r", "label": "% llamada → venta (cierre)", "tipo": "f", "f": "{ventas_r}/{llamadas_r}", "fmt": "pct", "bold": True},
        {"key": "costo_agenda_r", "label": "Costo por agenda", "tipo": "f", "f": "{inversion_r}/{agendas_r}", "fmt": "money"},
        {"key": "cac_r", "label": "CAC real", "tipo": "f", "f": "{inversion_r}/{ventas_r}", "fmt": "money"},
        *seguimiento_calc("inversion_r", "leads_r", "fact_r", "cash_r"),
    ]},
    "benchmarks": [
        {"metrica": "CPL (USD)", "niveles": [">6", "3 a 6", "1,5 a 3", "<1,5"], "key": "cpu", "fuente": "Hispano, ticket 500 a 3.000, 2024 a 2026."},
        {"metrica": "% lead → aplicación", "niveles": ["<5 %", "5 a 10 %", "10 a 18 %", ">18 %"], "key": "aplic_pct", "fuente": "Formulario largo. Con evento previo se mide sobre asistentes."},
        {"metrica": "% aplicación → calificado", "niveles": ["<40 %", "40 a 55 %", "55 a 70 %", ">70 %"], "key": "calif_pct", "fuente": "Depende de la dureza del filtro."},
        {"metrica": "% calificado → agenda", "niveles": ["<40 %", "40 a 55 %", "55 a 70 %", ">70 %"], "key": "agenda_pct", "fuente": "Mercado: 30 a 60 % de las aplicaciones terminan agendadas."},
        {"metrica": "% agenda → llamada (show)", "niveles": ["<55 %", "55 a 65 %", "65 a 75 %", ">75 %"], "key": "show_llamada", "fuente": "Mercado: no-show del 20 a 30 %; equipos muy buenos, 8 a 12 %."},
        {"metrica": "% llamada → venta (cierre)", "niveles": ["<15 %", "15 a 25 %", "25 a 35 %", ">35 %"], "key": "cierre", "fuente": "Lead tibio y filtrado: promedio 30 %. Sin filtro: menos de 5 %. Sin consenso por ticket."},
        {"metrica": "% lead → venta", "niveles": ["<0,4 %", "0,4 a 0,8 %", "0,8 a 1,5 %", ">1,5 %"], "key": "conv_unidad_venta", "fuente": "El producto de todas las conversiones."},
        {"metrica": "Costo por agenda (USD)", "niveles": [">250", "120 a 250", "60 a 120", "<60"], "key": "costo_agenda", "fuente": "Ticket 500 a 1.500."},
        {"metrica": "ROAS del cash del primer mes", "niveles": ["<1,0", "1,0 a 1,5", "1,5 a 2,5", ">2,5"], "key": "roas_cash_m1", "fuente": "Con cuotas. Sobre cobranza completa, sumá lo que falta cobrar."},
    ],
    "glosario": GLOSARIO_BASE + [("Aplicación", "Formulario largo que el lead completa para pedir una llamada. Filtra y le da información al closer.", "Supuestos"),
                                 ("Setter", "Persona que contacta a los que aplicaron, confirma y agenda. Cobra por contacto o por agenda.", "Supuestos"),
                                 ("Closer", "Quien hace la llamada de venta. Cobra comisión sobre el cash cobrado.", "Supuestos"),
                                 ("Show de la llamada", "Porcentaje de agendas que efectivamente ocurren.", "Supuestos")],
    "chequeos": chequeos_base(["ctr", "clic_visita", "conv_landing", "show_evento", "aplic_pct", "calif_pct", "agenda_pct", "show_llamada", "cierre", "ds_conv"],
                              [("unidades", "aplicaciones"), ("aplicaciones", "calificados"), ("calificados", "agendas"), ("agendas", "llamadas"), ("llamadas", "ventas_front")],
                              positivos=["cpm", "ctr", "clic_visita", "conv_landing"]) +
                [{"label": "El interruptor de evento previo es 0 o 1", "cond": "OR({hay_evento}=0,{hay_evento}=1)", "ayuda": "Supuestos → evento previo."}],
}

# ---------------------------------------------------------------- 4. WEBINAR PAGO
WEBINAR_PAGO = {
    "archivo": "04_Modelo_Financiero_Embudo_Webinar_Pago.xlsx",
    "titulo": "Modelo financiero · Embudo de webinar pago (evento pago)",
    "subtitulo": "Anuncios → página de ventas de la entrada → entrada + bump → grupo de WhatsApp → evento en vivo y replay → oferta → programa superior",
    "unidad_singular": "entrada", "unidad_plural": "entradas",
    "ganancia": [{"key": "visitas", "nombre": "visita", "bold": True, "como": "Ganancia del período ÷ visitas a la página de ventas. La métrica más valiosa: resume todo lo que pasa después. Su par es el costo por visita."},
                 {"key": "unidades", "nombre": "entrada", "bold": True, "como": "Ganancia del período ÷ entradas. Su par es el costo por entrada."},
                 {"key": "asist_vivo", "nombre": "asistente en vivo"},
                 {"key": "solicitudes", "nombre": "solicitud"},
                 {"key": "ventas_front", "nombre": "cliente", "bold": True, "como": "Ganancia del período ÷ compradores de la oferta. Su par es el costo por comprador."}],
    "embudo": [
        {"key": "visitas", "label": "Visitas a la página de ventas de la entrada", "nota": "Costo por visita."},
        {"key": "unidades", "label": "Compran la entrada", "vs": "visitas", "bold": True, "nota": "Costo por entrada. La unidad de este embudo: acá los leads ya son compradores."},
        {"key": "ventas_bump_e", "label": "Toman el bump de la entrada", "vs": "unidades", "costo": False, "techo": False, "nota": "Sobre compradores de entrada. Suma al ROAS del front."},
        {"key": "en_grupo", "label": "Entran al grupo de WhatsApp", "vs": "unidades", "nota": "Costo por persona en el grupo."},
        {"key": "asist_vivo", "label": "Asisten en vivo", "vs": "unidades", "bold": True, "nota": "Costo por asistente en vivo. Sobre compradores de entrada."},
        {"key": "asist_replay", "label": "Ven el replay", "vs": "unidades", "nota": "Sobre compradores de entrada."},
        {"key": "solic_vivo", "label": "Solicitan, de los que estuvieron en vivo", "vs": "asist_vivo", "nota": "Formulario de compra, aplicación o vendedor. Sobre asistentes en vivo."},
        {"key": "solic_replay", "label": "Solicitan, de los que vieron el replay", "vs": "asist_replay", "nota": "Sobre los que vieron el replay."},
        {"key": "solicitudes", "label": "Solicitudes (total)", "vs": "unidades", "bold": True, "nota": "Costo por solicitud. Sobre compradores de entrada."},
        {"key": "ventas_front", "label": "Compran la oferta", "vs": "solicitudes", "bold": True, "nota": "Costo por comprador de la oferta. Sobre solicitudes (cierre)."},
        {"key": "ventas_backend", "label": "Pasan al programa superior", "vs": "ventas_front", "costo": False, "techo": False, "nota": "Sobre compradores de la oferta."},
    ],
    "inicio": inicio("embudo de webinar pago: anuncios que venden una entrada barata a un evento, un grupo de WhatsApp, el evento en vivo (con replay) donde se presenta la oferta principal, y un programa superior que se vende después",
                     ["La unidad que comprás es la entrada vendida: acá los leads ya son compradores de un low ticket, no registros. Lo primero que se mira es qué parte de la pauta recupera la entrada (ROAS del front); después, escalón por escalón: costo por persona en el grupo, costo por asistente en vivo (mucho más alto que en gratuito porque pagaron), costo por solicitud y cierre, cada uno con su cantidad y su porcentaje."],
                     ["Un taller pago con entradas a 9 USD promedio (si escalonás 5, 10 y 15, poné el promedio cobrado). Se invierten 3.000 USD por lanzamiento a 0,35 por visita: 8.571 visitas, el 2,5 % compra la entrada (214 entradas, costo por entrada 14) y el 20 % suma un bump de 27.",
                      "El 85 % entra al grupo (costo por persona en el grupo cerca de 16), el 55 % asiste en vivo (costo por asistente cerca de 25) y el 25 % ve el replay. Cuando se presenta la oferta de 497, el 16 % de los asistentes en vivo solicita y el 4 % de los del replay; la mitad de las solicitudes termina en compra: unas 10 ventas, con un costo por solicitud cerca de 140. El 10 % de los compradores pasa a un programa de 1.997.",
                      "Costos: pasarela 8 %, reembolsos 5 %, 0,30 por entrada en WhatsApp y soporte, fijos 800 por lanzamiento. Cobranza 50 / 25 / 25.",
                      "Resultado: la entrada y el bump recuperan cerca del 100 % de la pauta en facturado (un 90 % en cash neto) antes del evento; la oferta y el programa son la ganancia. Cambiá los números por los tuyos."],
                     "entrada", "entradas", "lanzamiento",
                     ["8. El ROAS del front (entradas + bump ÷ inversión) es el seguro del embudo: si está cerca de 1, el evento se paga solo y todo lo demás es ganancia. Si cae por debajo de 0,5, revisá precio de la entrada y página de ventas antes que nada."]),
    "supuestos": [
        {"grupo": "1. Inversión y tráfico", "items": [
            {"key": "inversion", "label": "Inversión en publicidad por lanzamiento", "val": 3000, "fmt": "money0", "unidad": "USD / lanzamiento", "nota": "Un lanzamiento = una tanda de venta de entradas + evento + oferta."},
            {"key": "lanz_mes", "label": "Lanzamientos por mes (para la proyección)", "val": 2, "fmt": "int", "unidad": "lanzamientos / mes", "nota": "Cuántos eventos como este hacés por mes. La proyección multiplica inversión, costos fijos y ventas por este número."},
            {"key": "costo_visita", "label": "Costo por visita a la página de ventas de la entrada", "esc": (0.50, 0.35, 0.25), "fmt": "money", "unidad": "USD / visita", "nota": "Lo que pagás por cada persona que llega a la página."},
        ]},
        {"grupo": "2. Entrada y bump", "items": [
            {"key": "conv_entrada", "label": "% de visitas que compran la entrada", "esc": (0.015, 0.025, 0.035), "fmt": "pct", "unidad": "%", "nota": "Página de ventas de un producto de 5 a 15 USD."},
            {"key": "precio_entrada", "label": "Precio promedio cobrado por entrada", "val": 9, "fmt": "money", "unidad": "USD", "nota": "Si escalonás el precio (5 → 10 → 15), poné el promedio que cobrás."},
            {"key": "bump_e_precio", "label": "Bump en el checkout de la entrada: precio", "val": 27, "fmt": "money", "unidad": "USD", "nota": "Grabaciones, plantillas, acceso extendido."},
            {"key": "bump_e_conv", "label": "Bump: % de compradores de entrada que lo toman", "esc": (0.12, 0.20, 0.30), "fmt": "pct", "unidad": "%", "nota": ""},
        ]},
        {"grupo": "3. Grupo y asistencia (sobre compradores de entrada)", "items": [
            {"key": "grupo_pct", "label": "% que entra al grupo de WhatsApp", "esc": (0.70, 0.85, 0.95), "fmt": "pct", "unidad": "%", "nota": "Pagaron: entran casi todos."},
            {"key": "show_vivo", "label": "% que asiste en vivo", "esc": (0.40, 0.55, 0.65), "fmt": "pct", "unidad": "%", "nota": "Mucho más alto que en gratuito."},
            {"key": "show_replay", "label": "% que ve el replay (sin contar los que fueron en vivo)", "esc": (0.15, 0.25, 0.30), "fmt": "pct", "unidad": "%", "nota": ""},
        ]},
        {"grupo": "4. Oferta del evento y programa superior", "items": [
            {"key": "precio_oferta", "label": "Oferta principal: precio", "val": 497, "fmt": "money", "unidad": "USD", "nota": "Lo que se presenta al final del evento."},
            {"key": "solic_vivo_pct", "label": "% de asistentes en vivo que solicitan (formulario de compra, de aplicación o hablar con un vendedor)", "esc": (0.10, 0.16, 0.22), "fmt": "pct", "unidad": "%", "nota": "Público que pagó por estar: solicita más que en un webinar gratuito."},
            {"key": "solic_replay_pct", "label": "% de los que ven el replay que solicitan", "esc": (0.02, 0.04, 0.06), "fmt": "pct", "unidad": "%", "nota": ""},
            {"key": "cierre_pct", "label": "% de solicitudes que terminan en compra", "esc": (0.40, 0.50, 0.60), "fmt": "pct", "unidad": "%", "nota": "Con compra directa en el formulario suele ser alto; con vendedor, 40 a 60 %."},
            {"key": "backend_precio", "label": "Programa superior: precio", "val": 1997, "fmt": "money", "unidad": "USD", "nota": "Por llamada o por ascenso."},
            {"key": "backend_conv", "label": "Programa superior: % de compradores de la oferta que lo toman", "esc": (0.05, 0.10, 0.15), "fmt": "pct", "unidad": "%", "nota": ""},
        ]},
        {"grupo": "5. Costos", "items": costos(0.08, 0.0, 0.05, 0.30, "entrada", 800, "lanzamiento",
                                                 "Sobre el cash cobrado. Si el programa superior se vende por llamada, poné acá la comisión del closer.",
                                                 "WhatsApp, soporte, plataforma del evento: lo que pagás por cada entrada.")},
        {"grupo": "6. Cobranza", "items": cobranza(0.50, 0.25, 0.25, "Se aplica a todo el facturado como promedio ponderado: la entrada se cobra al contado, la oferta y el programa en cuotas. El ejemplo usa 50 / 25 / 25.")},
        {"grupo": "7. Objetivos y proyección", "items": objetivos(2.0, 25, "ventas de la oferta / lanzamiento", 4000, "lanzamiento")},
    ],
    "calculo": [
        {"seccion": "Tráfico y entradas"},
        {"key": "visitas", "label": "Visitas a la página de ventas", "f": "{inversion}/{costo_visita}", "fmt": "int", "como": "Inversión ÷ costo por visita."},
        {"key": "cpu", "label": "Costo por entrada vendida", "f": "{costo_visita}/{conv_entrada}", "fmt": "money", "como": "Costo por visita ÷ % que compra la entrada.", "bold": True},
        {"key": "unidades", "label": "Entradas vendidas", "f": "{inversion}/{cpu}", "fmt": "int", "como": "Inversión ÷ costo por entrada.", "bold": True},
        {"key": "fact_entradas", "label": "Facturado: entradas", "f": "{unidades}*{precio_entrada}", "fmt": "money0", "como": "Entradas × precio promedio."},
        {"key": "ventas_bump_e", "label": "Ventas: bump de la entrada", "f": "{unidades}*{bump_e_conv}", "fmt": "num1", "como": "Entradas × % que lo toma."},
        {"key": "fact_bump_e", "label": "Facturado: bump de la entrada", "f": "{ventas_bump_e}*{bump_e_precio}", "fmt": "money0", "como": "Ventas × precio."},
        {"key": "fact_frontend", "label": "Facturado del front (entradas + bump)", "f": "{fact_entradas}+{fact_bump_e}", "fmt": "money0", "como": "Lo que entra antes del evento.", "bold": True},
        {"key": "roas_front", "label": "ROAS del front (qué parte de la pauta recupera la entrada)", "f": "{fact_frontend}/{inversion}", "fmt": "ratio", "como": "Facturado del front ÷ inversión. Cerca de 1 = el evento se paga solo.", "bold": True},
        {"seccion": "Grupo y asistencia"},
        {"key": "en_grupo", "label": "Personas en el grupo", "f": "{unidades}*{grupo_pct}", "fmt": "int", "como": "Entradas × % que entra."},
        {"key": "costo_grupo", "label": "Costo por persona en el grupo", "f": "{inversion}/{en_grupo}", "fmt": "money", "como": "Inversión ÷ personas en el grupo.", "bold": True},
        {"key": "asist_vivo", "label": "Asistentes en vivo", "f": "{unidades}*{show_vivo}", "fmt": "int", "como": "Entradas × asistencia en vivo.", "bold": True},
        {"key": "asist_replay", "label": "Vieron el replay", "f": "{unidades}*{show_replay}", "fmt": "int", "como": "Entradas × % que ve el replay."},
        {"key": "costo_asistente", "label": "Costo por asistente en vivo", "f": "{inversion}/{asist_vivo}", "fmt": "money", "como": "Inversión ÷ asistentes."},
        {"seccion": "Solicitudes (formulario de compra, aplicación o vendedor), oferta, programa y facturación"},
        {"key": "solic_vivo", "label": "Solicitudes: en vivo", "f": "{asist_vivo}*{solic_vivo_pct}", "fmt": "num1", "como": "Asistentes en vivo × % que solicita."},
        {"key": "solic_replay", "label": "Solicitudes: replay", "f": "{asist_replay}*{solic_replay_pct}", "fmt": "num1", "como": "Replay × % que solicita."},
        {"key": "solicitudes", "label": "Solicitudes (total)", "f": "{solic_vivo}+{solic_replay}", "fmt": "num1", "como": "En vivo + replay.", "bold": True},
        {"key": "solic_sobre_unidades", "label": "% de compradores de entrada que solicitan", "f": "{solicitudes}/{unidades}", "fmt": "pct2", "como": "Solicitudes ÷ entradas."},
        {"key": "costo_solicitud", "label": "Costo por solicitud", "f": "{inversion}/{solicitudes}", "fmt": "money", "como": "Inversión ÷ solicitudes.", "bold": True},
        {"key": "ventas_front", "label": "Ventas de la oferta", "f": "{solicitudes}*{cierre_pct}", "fmt": "num1", "como": "Solicitudes × % que termina en compra.", "bold": True},
        {"key": "conv_unidad_venta", "label": "% de compradores de entrada que compran la oferta", "f": "{ventas_front}/{unidades}", "fmt": "pct2", "como": "Ventas ÷ entradas."},
        {"key": "cpa", "label": "Costo por comprador de la oferta", "f": "{inversion}/{ventas_front}", "fmt": "money", "como": "Inversión ÷ ventas de la oferta.", "bold": True},
        {"key": "fact_front", "label": "Facturado: oferta", "f": "{ventas_front}*{precio_oferta}", "fmt": "money0", "como": "Ventas × precio."},
        {"key": "ventas_backend", "label": "Ventas: programa superior", "f": "{ventas_front}*{backend_conv}", "fmt": "num1", "como": "Compradores de la oferta × % que asciende."},
        {"key": "fact_backend", "label": "Facturado: programa superior", "f": "{ventas_backend}*{backend_precio}", "fmt": "money0", "como": "Ventas × precio."},
        {"key": "facturado", "label": "Facturado total", "f": "{fact_frontend}+{fact_front}+{fact_backend}", "fmt": "money0", "como": "Front + oferta + programa.", "bold": True},
        {"key": "aov", "label": "Facturado por comprador de la oferta", "f": "{facturado}/{ventas_front}", "fmt": "money", "como": "Facturado total ÷ ventas de la oferta."},
        {"key": "ventas_por_unidad", "label": "Ventas de la oferta por entrada (para la proyección)", "f": "{ventas_front}/{unidades}", "fmt": "pct2", "como": "Igual a '% que compra la oferta'."},
        {"key": "fact_por_unidad", "label": "Facturado por entrada", "f": "{facturado}/{unidades}", "fmt": "money", "como": "Facturado total ÷ entradas."},
        *cash_rows("entrada"),
        {"seccion": "Cuánto vale cada entrada y hasta cuánto pagar"},
        {"key": "vpu", "label": "Valor neto por entrada", "f": "({neto}-{semivar})/{unidades}", "fmt": "money", "como": "(Cash neto − costos por entrada) ÷ entradas.", "bold": True},
        {"key": "techo_cpu", "label": "Techo de costo por entrada (break-even)", "f": "{vpu}", "fmt": "money", "como": "Igual al valor neto por entrada.", "bold": True},
        {"key": "objetivo_cpu", "label": "Objetivo de costo por entrada", "f": "{techo_cpu}/(1+{margen_seg})", "fmt": "money", "como": "Techo ÷ (1 + margen de seguridad).", "bold": True},
        {"key": "techo_visita", "label": "Techo de costo por visita a la página", "f": "{vpu}*{conv_entrada}", "fmt": "money", "como": "Valor por entrada × % que compra la entrada."},
        {"key": "techo_asistente", "label": "Techo de costo por asistente en vivo", "f": "{vpu}/{show_vivo}", "fmt": "money", "como": "Valor por entrada ÷ asistencia."},
        {"key": "techo_solicitud", "label": "Techo de costo por solicitud", "f": "{vpu}*{unidades}/{solicitudes}", "fmt": "money", "como": "Valor total ÷ solicitudes.", "bold": True},
        {"key": "techo_cpa", "label": "Techo de costo por comprador de la oferta", "f": "{vpu}/{conv_unidad_venta}", "fmt": "money", "como": "Valor por entrada ÷ % que compra la oferta."},
        {"key": "objetivo_cpa", "label": "Objetivo de costo por comprador de la oferta", "f": "{techo_cpa}/(1+{margen_seg})", "fmt": "money", "como": "Techo ÷ (1 + margen de seguridad)."},
        {"seccion": "Semáforo y cuánto invertir"},
        {"key": "semaforo", "label": "Semáforo del costo por entrada actual", "f": 'IF({cpu}>{techo_cpu},"ROJO",IF(AND({cpu}<={objetivo_cpu},{roas_cash}>={roas_obj}),"VERDE","AMARILLO"))', "fmt": "txt", "como": "Rojo: costo > techo. Verde: costo ≤ objetivo y ROAS sobre cash neto ≥ objetivo. Amarillo: el resto.", "bold": True},
        {"key": "inv_meta", "label": "Inversión necesaria para la meta de ventas de la oferta (al costo actual)", "f": 'IF({conv_unidad_venta}=0,"inalcanzable con estos supuestos",{meta_ventas}/{conv_unidad_venta}*{cpu})', "fmt": "money0", "como": "Meta ÷ % que compra la oferta × costo por entrada.", "bold": True},
        {"key": "inv_meta_obj", "label": "Inversión para la meta al costo objetivo (lo máximo que conviene pagar)", "f": 'IF({conv_unidad_venta}=0,"inalcanzable con estos supuestos",{meta_ventas}/{conv_unidad_venta}*{objetivo_cpu})', "fmt": "money0", "como": "Lo mismo, al costo objetivo."},
    ],
    "resumen": [
        {"seccion": "Resultado del lanzamiento"},
        {"key": "profit", "que": "Cash neto menos costos y menos inversión."},
        {"key": "roas_front", "que": "Qué parte de la pauta recupera la entrada antes del evento. Cerca de 1 = el evento se paga solo."},
        {"key": "roas_cash", "que": "Total, sobre cash neto."},
        {"key": "unidades", "que": "Entradas vendidas."},
        {"key": "asist_vivo", "que": "Asistentes en vivo."},
        {"key": "ventas_front", "que": "Ventas de la oferta (vivo + replay)."},
        {"seccion": "Unit economics"},
        {"key": "cpu", "que": "Costo por entrada vendida."},
        {"key": "vpu", "que": "Lo que vale una entrada en cash neto, con todo lo que viene después."},
        {"key": "costo_grupo", "que": "Lo que te cuesta cada persona que entra al grupo."},
        {"key": "costo_asistente", "que": "Lo que te cuesta cada asistente en vivo."},
        {"key": "solicitudes", "que": "Formularios de compra, aplicaciones o pedidos de hablar con un vendedor."},
        {"key": "costo_solicitud", "que": "Lo que te cuesta cada solicitud."},
        {"key": "cpa", "que": "Lo que te cuesta cada comprador de la oferta."},
        {"seccion": "Las dos caras de cada número"},
        {"key": "gan_visitas", "que": "Lo que te queda por cada visita a la página de ventas. La métrica más valiosa del embudo."},
        {"key": "gan_unidades", "que": "Lo que te queda por cada entrada vendida. Su par es el costo por entrada."},
        {"key": "gan_ventas_front", "que": "Lo que te queda por cada comprador de la oferta. Su par es el costo por comprador."},
        {"key": "aov", "label": "Order value (AOV)", "que": "Facturado por comprador de la oferta, con todo lo demás."},
        {"key": "aov_neto", "label": "Order value neto (AOV neto)", "que": "Lo mismo después de comisiones, reembolsos y costos por entrada."},
        {"seccion": "Hasta cuánto pagar"},
        {"key": "techo_cpu", "que": "Costo por entrada donde no ganás ni perdés."},
        {"key": "objetivo_cpu", "que": "A este costo o menos estás en verde."},
        {"key": "techo_visita", "que": "Costo máximo por visita a la página de ventas."},
        {"key": "techo_solicitud", "que": "Costo máximo por solicitud."},
        {"key": "techo_cpa", "que": "Costo máximo por comprador de la oferta."},
        {"key": "semaforo", "que": "Tu costo por entrada actual contra techo y objetivo."},
        {"seccion": "Cuánto invertir y cuánta caja"},
        {"key": "inv_meta", "que": "Para la meta de ventas de Supuestos, al costo actual."},
        {"key": "caja_necesaria", "label": "Caja que hay que tener (peor momento de la proyección)", "que": "Si da 0, el embudo se autofinancia: cada mes cobra más de lo que invierte."},
        {"key": "caja_minima", "label": "Saldo mínimo de caja con tu caja inicial", "que": "Si es negativo, la caja inicial no alcanza."},
        {"key": "profit_12m", "label": "Ganancia acumulada en 12 meses", "que": "Con la inversión creciendo según el supuesto."},
    ],
    "tablas": [
        {"titulo": "Precio de la oferta × % de solicitudes que terminan en compra → ganancia del lanzamiento", "nota": "A más precio, menos cierre: la tabla muestra qué combinación gana.",
         "fila_key": "precio_oferta", "fila_label": "Precio", "filas": [197, 297, 497, 997, 1997], "fila_fmt": "money0",
         "col_key": "cierre_pct", "col_label": "% solicitud → compra", "cols": [0.30, 0.40, 0.50, 0.60, 0.70], "col_fmt": "pct", "salida": "profit", "salida_fmt": "money0"},
        {"titulo": "Costo por entrada × % de asistentes en vivo que solicitan → ganancia del lanzamiento", "nota": "Hasta cuánto pagar por cada entrada según lo que mueve el evento.",
         "fila_key": "cpu", "fila_label": "Costo por entrada", "filas": [8, 12, 15, 20, 30, 40], "fila_fmt": "money",
         "col_key": "solic_vivo_pct", "col_label": "% en vivo que solicita", "cols": [0.08, 0.12, 0.16, 0.20, 0.25], "col_fmt": "pct", "salida": "profit", "salida_fmt": "money0"},
    ],
    "tabla_roas": {"titulo": "Cuánto invertir para una facturación objetivo por lanzamiento, según el ROAS que querés", "nota": "Inversión = facturación ÷ ROAS. Debajo: cuántas entradas hacen falta y cuánto podés pagar por cada una.",
                   "facturacion": [5000, 10000, 20000, 30000, 50000], "roas": [1.5, 2.0, 2.5, 3.0, 4.0], "unidad_label": "Entradas", "unidad_singular": "entrada"},
    "palancas": [
        {"key": "costo_visita", "mult": 0.9, "label": "Costo por visita 10 % más barato"},
        {"key": "conv_entrada", "mult": 1.1, "label": "Página de la entrada 10 % más conversión"},
        {"key": "precio_entrada", "mult": 1.1, "label": "Precio de la entrada 10 % más alto (misma conversión)"},
        {"key": "show_vivo", "mult": 1.1, "label": "Asistencia en vivo 10 % más alta"},
        {"key": "solic_vivo_pct", "mult": 1.1, "label": "10 % más asistentes en vivo que solicitan (oferta, pitch)"},
        {"key": "cierre_pct", "mult": 1.1, "label": "10 % más solicitudes que terminan en compra (seguimiento, vendedor)"},
        {"key": "precio_oferta", "mult": 1.1, "label": "Precio de la oferta 10 % más alto (misma conversión)"},
        {"key": "backend_conv", "mult": 1.1, "label": "Programa superior 10 % más tomado"},
        {"key": "bump_e_conv", "mult": 1.1, "label": "Bump de la entrada 10 % más tomado"},
    ],
    "seguimiento": {"periodo": "lanzamiento", "filas": [
        {"seccion": "Datos que cargás"},
        {"key": "inversion_r", "label": "Inversión en publicidad", "tipo": "in", "fmt": "money0", "ejemplo": [3000, 3200, 3600]},
        {"key": "visitas_r", "label": "Visitas a la página de ventas", "tipo": "in", "fmt": "int", "ejemplo": [8600, 8900, 9700]},
        {"key": "entradas_r", "label": "Entradas vendidas", "tipo": "in", "fmt": "int", "ejemplo": [214, 220, 235]},
        {"key": "bump_r", "label": "Bumps de la entrada", "tipo": "in", "fmt": "int", "ejemplo": [43, 40, 50]},
        {"key": "grupo_r", "label": "Entraron al grupo", "tipo": "in", "fmt": "int", "ejemplo": [182, 190, 200]},
        {"key": "vivo_r", "label": "Asistentes en vivo", "tipo": "in", "fmt": "int", "ejemplo": [118, 115, 135]},
        {"key": "replay_r", "label": "Vieron el replay", "tipo": "in", "fmt": "int", "ejemplo": [54, 60, 58]},
        {"key": "solic_r", "label": "Solicitudes (formulario de compra, aplicación o vendedor)", "tipo": "in", "fmt": "int", "ejemplo": [22, 19, 26]},
        {"key": "ventas_r", "label": "Ventas de la oferta", "tipo": "in", "fmt": "int", "ejemplo": [11, 9, 13]},
        {"key": "backend_r", "label": "Ventas del programa superior", "tipo": "in", "fmt": "int", "ejemplo": [1, 1, 2]},
        {"key": "fact_r", "label": "Facturado del lanzamiento (a precio de lista, con cuotas por cobrar)", "tipo": "in", "fmt": "money0", "ejemplo": [10400, 9000, 12300]},
        {"key": "cash_r", "label": "Cash cobrado hasta ahora de ese lanzamiento", "tipo": "in", "fmt": "money0", "ejemplo": [6900, 6300, 8200]},
        {"seccion": "Lo que calcula el modelo"},
        {"key": "cpu_r", "label": "Costo por entrada real", "tipo": "f", "f": "{inversion_r}/{entradas_r}", "fmt": "money", "bold": True},
        {"key": "conv_e_r", "label": "% visita → entrada", "tipo": "f", "f": "{entradas_r}/{visitas_r}", "fmt": "pct"},
        {"key": "roas_front_r", "label": "ROAS del front (entradas × precio + bumps × precio ÷ inversión)", "tipo": "f", "f": "({entradas_r}*{precio_entrada}+{bump_r}*{bump_e_precio})/{inversion_r}", "fmt": "ratio", "bold": True},
        {"key": "show_r", "label": "% entrada → en vivo", "tipo": "f", "f": "{vivo_r}/{entradas_r}", "fmt": "pct"},
        {"key": "conv_vivo_r", "label": "Ventas ÷ asistentes en vivo", "tipo": "f", "f": "{ventas_r}/{vivo_r}", "fmt": "pct"},
        {"key": "cpa_r", "label": "Costo por comprador de la oferta", "tipo": "f", "f": "{inversion_r}/{ventas_r}", "fmt": "money"},
        {"key": "costo_grupo_r", "label": "Costo por persona en el grupo", "tipo": "f", "f": "{inversion_r}/{grupo_r}", "fmt": "money"},
        {"key": "solic_pct_r", "label": "% en vivo → solicitud", "tipo": "f", "f": "{solic_r}/{vivo_r}", "fmt": "pct"},
        {"key": "costo_solic_r", "label": "Costo por solicitud", "tipo": "f", "f": "{inversion_r}/{solic_r}", "fmt": "money", "bold": True},
        {"key": "cierre_r", "label": "% solicitud → compra", "tipo": "f", "f": "{ventas_r}/{solic_r}", "fmt": "pct"},
        *seguimiento_calc("inversion_r", "entradas_r", "fact_r", "cash_r"),
    ]},
    "benchmarks": [
        {"metrica": "ROAS del front (entradas + bump ÷ inversión)", "niveles": ["<0,5", "0,5 a 0,8", "0,8 a 1,2", ">1,2"], "key": "roas_front", "fuente": "Eventos pagos hispanos, 2025 a 2026. Cerca de 1 el evento se paga solo."},
        {"metrica": "% visitas → entrada", "niveles": ["<1 %", "1 a 2 %", "2 a 3,5 %", ">3,5 %"], "key": "conv_entrada", "fuente": "Página de ventas de 5 a 15 USD."},
        {"metrica": "Costo por entrada (USD)", "niveles": [">25", "15 a 25", "8 a 15", "<8"], "key": "cpu", "fuente": "Depende del precio: compará contra tu precio de entrada."},
        {"metrica": "% entrada → en vivo", "niveles": ["<35 %", "35 a 50 %", "50 a 65 %", ">65 %"], "key": "show_vivo", "fuente": "Pagaron: asisten mucho más que en gratuito (10 a 20 %)."},
        {"metrica": "Costo por persona en el grupo (USD)", "niveles": [">30", "18 a 30", "10 a 18", "<10"], "key": "costo_grupo", "fuente": "Sobre compradores de entrada: casi todos entran."},
        {"metrica": "% asistentes en vivo que solicitan", "niveles": ["<8 %", "8 a 14 %", "14 a 22 %", ">22 %"], "key": "solic_vivo_pct", "fuente": "Público que pagó por estar: solicita más que en gratuito."},
        {"metrica": "Costo por solicitud (USD)", "niveles": [">250", "150 a 250", "80 a 150", "<80"], "key": "costo_solicitud", "fuente": "Oferta de 300 a 1.000."},
        {"metrica": "% solicitud → compra", "niveles": ["<35 %", "35 a 50 %", "50 a 65 %", ">65 %"], "key": "cierre_pct", "fuente": "Con vendedor: 40 a 60 %. Compra directa en el formulario: más alto."},
        {"metrica": "% entrada → oferta (total)", "niveles": ["<3 %", "3 a 6 %", "6 a 10 %", ">10 %"], "key": "conv_unidad_venta", "fuente": "Vivo + replay."},
        {"metrica": "ROAS total sobre cash neto", "niveles": ["<1,3", "1,3 a 2", "2 a 3", ">3"], "key": "roas_cash", "fuente": "Por lanzamiento, cobranza completa."},
    ],
    "glosario": GLOSARIO_BASE + [("Entrada", "El producto barato (5 a 15 USD) que da acceso al evento. Es la unidad de adquisición de este embudo.", "Supuestos"),
                                 ("ROAS del front", "Facturado de entradas y bump dividido por la inversión: qué parte de la pauta se recupera antes del evento.", "Modelo"),
                                 ("Precio escalonado", "Entrada que sube de precio a medida que se acerca el evento (5 → 10 → 15). En el modelo se usa el promedio cobrado.", "Supuestos"),
                                 ("Solicitud", "Lo que hace el asistente cuando se presenta la oferta: completa el formulario de compra, la aplicación, o pide hablar con un vendedor. Se mide en cantidad, costo por solicitud y % sobre asistentes en vivo.", "Modelo, Seguimiento")],
    "chequeos": chequeos_base(["conv_entrada", "bump_e_conv", "grupo_pct", "show_vivo", "show_replay", "solic_vivo_pct", "solic_replay_pct", "cierre_pct", "backend_conv"],
                              [("visitas", "unidades"), ("unidades", "asist_vivo"), ("asist_vivo", "solic_vivo"), ("asist_replay", "solic_replay"), ("solicitudes", "ventas_front")],
                              positivos=["costo_visita", "conv_entrada"],
                              extra=[{"label": "En vivo + replay no superan el 100 % de los compradores", "cond": "({show_vivo}+{show_replay})<=1", "ayuda": "El replay se cuenta sin los que fueron en vivo."}]),
}
